// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentmapgh/internal/ent/duplicatecandidate"
	"rentmapgh/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DuplicateCandidateUpdate is the builder for updating DuplicateCandidate entities.
type DuplicateCandidateUpdate struct {
	config
	hooks    []Hook
	mutation *DuplicateCandidateMutation
}

// Where appends a list predicates to the DuplicateCandidateUpdate builder.
func (_u *DuplicateCandidateUpdate) Where(ps ...predicate.DuplicateCandidate) *DuplicateCandidateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DuplicateCandidateUpdate) SetUpdatedAt(v time.Time) *DuplicateCandidateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDistanceM sets the "distance_m" field.
func (_u *DuplicateCandidateUpdate) SetDistanceM(v int) *DuplicateCandidateUpdate {
	_u.mutation.ResetDistanceM()
	_u.mutation.SetDistanceM(v)
	return _u
}

// SetNillableDistanceM sets the "distance_m" field if the given value is not nil.
func (_u *DuplicateCandidateUpdate) SetNillableDistanceM(v *int) *DuplicateCandidateUpdate {
	if v != nil {
		_u.SetDistanceM(*v)
	}
	return _u
}

// AddDistanceM adds value to the "distance_m" field.
func (_u *DuplicateCandidateUpdate) AddDistanceM(v int) *DuplicateCandidateUpdate {
	_u.mutation.AddDistanceM(v)
	return _u
}

// SetPhotoBits sets the "photo_bits" field.
func (_u *DuplicateCandidateUpdate) SetPhotoBits(v int) *DuplicateCandidateUpdate {
	_u.mutation.ResetPhotoBits()
	_u.mutation.SetPhotoBits(v)
	return _u
}

// SetNillablePhotoBits sets the "photo_bits" field if the given value is not nil.
func (_u *DuplicateCandidateUpdate) SetNillablePhotoBits(v *int) *DuplicateCandidateUpdate {
	if v != nil {
		_u.SetPhotoBits(*v)
	}
	return _u
}

// AddPhotoBits adds value to the "photo_bits" field.
func (_u *DuplicateCandidateUpdate) AddPhotoBits(v int) *DuplicateCandidateUpdate {
	_u.mutation.AddPhotoBits(v)
	return _u
}

// ClearPhotoBits clears the value of the "photo_bits" field.
func (_u *DuplicateCandidateUpdate) ClearPhotoBits() *DuplicateCandidateUpdate {
	_u.mutation.ClearPhotoBits()
	return _u
}

// SetTextSimilarity sets the "text_similarity" field.
func (_u *DuplicateCandidateUpdate) SetTextSimilarity(v float64) *DuplicateCandidateUpdate {
	_u.mutation.ResetTextSimilarity()
	_u.mutation.SetTextSimilarity(v)
	return _u
}

// SetNillableTextSimilarity sets the "text_similarity" field if the given value is not nil.
func (_u *DuplicateCandidateUpdate) SetNillableTextSimilarity(v *float64) *DuplicateCandidateUpdate {
	if v != nil {
		_u.SetTextSimilarity(*v)
	}
	return _u
}

// AddTextSimilarity adds value to the "text_similarity" field.
func (_u *DuplicateCandidateUpdate) AddTextSimilarity(v float64) *DuplicateCandidateUpdate {
	_u.mutation.AddTextSimilarity(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *DuplicateCandidateUpdate) SetScore(v int) *DuplicateCandidateUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *DuplicateCandidateUpdate) SetNillableScore(v *int) *DuplicateCandidateUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *DuplicateCandidateUpdate) AddScore(v int) *DuplicateCandidateUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DuplicateCandidateUpdate) SetStatus(v duplicatecandidate.Status) *DuplicateCandidateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DuplicateCandidateUpdate) SetNillableStatus(v *duplicatecandidate.Status) *DuplicateCandidateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHandledBy sets the "handled_by" field.
func (_u *DuplicateCandidateUpdate) SetHandledBy(v uuid.UUID) *DuplicateCandidateUpdate {
	_u.mutation.SetHandledBy(v)
	return _u
}

// SetNillableHandledBy sets the "handled_by" field if the given value is not nil.
func (_u *DuplicateCandidateUpdate) SetNillableHandledBy(v *uuid.UUID) *DuplicateCandidateUpdate {
	if v != nil {
		_u.SetHandledBy(*v)
	}
	return _u
}

// ClearHandledBy clears the value of the "handled_by" field.
func (_u *DuplicateCandidateUpdate) ClearHandledBy() *DuplicateCandidateUpdate {
	_u.mutation.ClearHandledBy()
	return _u
}

// SetHandledAt sets the "handled_at" field.
func (_u *DuplicateCandidateUpdate) SetHandledAt(v time.Time) *DuplicateCandidateUpdate {
	_u.mutation.SetHandledAt(v)
	return _u
}

// SetNillableHandledAt sets the "handled_at" field if the given value is not nil.
func (_u *DuplicateCandidateUpdate) SetNillableHandledAt(v *time.Time) *DuplicateCandidateUpdate {
	if v != nil {
		_u.SetHandledAt(*v)
	}
	return _u
}

// ClearHandledAt clears the value of the "handled_at" field.
func (_u *DuplicateCandidateUpdate) ClearHandledAt() *DuplicateCandidateUpdate {
	_u.mutation.ClearHandledAt()
	return _u
}

// Mutation returns the DuplicateCandidateMutation object of the builder.
func (_u *DuplicateCandidateUpdate) Mutation() *DuplicateCandidateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DuplicateCandidateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DuplicateCandidateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DuplicateCandidateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DuplicateCandidateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DuplicateCandidateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := duplicatecandidate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DuplicateCandidateUpdate) check() error {
	if v, ok := _u.mutation.DistanceM(); ok {
		if err := duplicatecandidate.DistanceMValidator(v); err != nil {
			return &ValidationError{Name: "distance_m", err: fmt.Errorf(`ent: validator failed for field "DuplicateCandidate.distance_m": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := duplicatecandidate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DuplicateCandidate.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DuplicateCandidateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(duplicatecandidate.Table, duplicatecandidate.Columns, sqlgraph.NewFieldSpec(duplicatecandidate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(duplicatecandidate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DistanceM(); ok {
		_spec.SetField(duplicatecandidate.FieldDistanceM, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDistanceM(); ok {
		_spec.AddField(duplicatecandidate.FieldDistanceM, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PhotoBits(); ok {
		_spec.SetField(duplicatecandidate.FieldPhotoBits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPhotoBits(); ok {
		_spec.AddField(duplicatecandidate.FieldPhotoBits, field.TypeInt, value)
	}
	if _u.mutation.PhotoBitsCleared() {
		_spec.ClearField(duplicatecandidate.FieldPhotoBits, field.TypeInt)
	}
	if value, ok := _u.mutation.TextSimilarity(); ok {
		_spec.SetField(duplicatecandidate.FieldTextSimilarity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTextSimilarity(); ok {
		_spec.AddField(duplicatecandidate.FieldTextSimilarity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(duplicatecandidate.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(duplicatecandidate.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(duplicatecandidate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HandledBy(); ok {
		_spec.SetField(duplicatecandidate.FieldHandledBy, field.TypeUUID, value)
	}
	if _u.mutation.HandledByCleared() {
		_spec.ClearField(duplicatecandidate.FieldHandledBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.HandledAt(); ok {
		_spec.SetField(duplicatecandidate.FieldHandledAt, field.TypeTime, value)
	}
	if _u.mutation.HandledAtCleared() {
		_spec.ClearField(duplicatecandidate.FieldHandledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{duplicatecandidate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DuplicateCandidateUpdateOne is the builder for updating a single DuplicateCandidate entity.
type DuplicateCandidateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DuplicateCandidateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DuplicateCandidateUpdateOne) SetUpdatedAt(v time.Time) *DuplicateCandidateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDistanceM sets the "distance_m" field.
func (_u *DuplicateCandidateUpdateOne) SetDistanceM(v int) *DuplicateCandidateUpdateOne {
	_u.mutation.ResetDistanceM()
	_u.mutation.SetDistanceM(v)
	return _u
}

// SetNillableDistanceM sets the "distance_m" field if the given value is not nil.
func (_u *DuplicateCandidateUpdateOne) SetNillableDistanceM(v *int) *DuplicateCandidateUpdateOne {
	if v != nil {
		_u.SetDistanceM(*v)
	}
	return _u
}

// AddDistanceM adds value to the "distance_m" field.
func (_u *DuplicateCandidateUpdateOne) AddDistanceM(v int) *DuplicateCandidateUpdateOne {
	_u.mutation.AddDistanceM(v)
	return _u
}

// SetPhotoBits sets the "photo_bits" field.
func (_u *DuplicateCandidateUpdateOne) SetPhotoBits(v int) *DuplicateCandidateUpdateOne {
	_u.mutation.ResetPhotoBits()
	_u.mutation.SetPhotoBits(v)
	return _u
}

// SetNillablePhotoBits sets the "photo_bits" field if the given value is not nil.
func (_u *DuplicateCandidateUpdateOne) SetNillablePhotoBits(v *int) *DuplicateCandidateUpdateOne {
	if v != nil {
		_u.SetPhotoBits(*v)
	}
	return _u
}

// AddPhotoBits adds value to the "photo_bits" field.
func (_u *DuplicateCandidateUpdateOne) AddPhotoBits(v int) *DuplicateCandidateUpdateOne {
	_u.mutation.AddPhotoBits(v)
	return _u
}

// ClearPhotoBits clears the value of the "photo_bits" field.
func (_u *DuplicateCandidateUpdateOne) ClearPhotoBits() *DuplicateCandidateUpdateOne {
	_u.mutation.ClearPhotoBits()
	return _u
}

// SetTextSimilarity sets the "text_similarity" field.
func (_u *DuplicateCandidateUpdateOne) SetTextSimilarity(v float64) *DuplicateCandidateUpdateOne {
	_u.mutation.ResetTextSimilarity()
	_u.mutation.SetTextSimilarity(v)
	return _u
}

// SetNillableTextSimilarity sets the "text_similarity" field if the given value is not nil.
func (_u *DuplicateCandidateUpdateOne) SetNillableTextSimilarity(v *float64) *DuplicateCandidateUpdateOne {
	if v != nil {
		_u.SetTextSimilarity(*v)
	}
	return _u
}

// AddTextSimilarity adds value to the "text_similarity" field.
func (_u *DuplicateCandidateUpdateOne) AddTextSimilarity(v float64) *DuplicateCandidateUpdateOne {
	_u.mutation.AddTextSimilarity(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *DuplicateCandidateUpdateOne) SetScore(v int) *DuplicateCandidateUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *DuplicateCandidateUpdateOne) SetNillableScore(v *int) *DuplicateCandidateUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *DuplicateCandidateUpdateOne) AddScore(v int) *DuplicateCandidateUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DuplicateCandidateUpdateOne) SetStatus(v duplicatecandidate.Status) *DuplicateCandidateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DuplicateCandidateUpdateOne) SetNillableStatus(v *duplicatecandidate.Status) *DuplicateCandidateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHandledBy sets the "handled_by" field.
func (_u *DuplicateCandidateUpdateOne) SetHandledBy(v uuid.UUID) *DuplicateCandidateUpdateOne {
	_u.mutation.SetHandledBy(v)
	return _u
}

// SetNillableHandledBy sets the "handled_by" field if the given value is not nil.
func (_u *DuplicateCandidateUpdateOne) SetNillableHandledBy(v *uuid.UUID) *DuplicateCandidateUpdateOne {
	if v != nil {
		_u.SetHandledBy(*v)
	}
	return _u
}

// ClearHandledBy clears the value of the "handled_by" field.
func (_u *DuplicateCandidateUpdateOne) ClearHandledBy() *DuplicateCandidateUpdateOne {
	_u.mutation.ClearHandledBy()
	return _u
}

// SetHandledAt sets the "handled_at" field.
func (_u *DuplicateCandidateUpdateOne) SetHandledAt(v time.Time) *DuplicateCandidateUpdateOne {
	_u.mutation.SetHandledAt(v)
	return _u
}

// SetNillableHandledAt sets the "handled_at" field if the given value is not nil.
func (_u *DuplicateCandidateUpdateOne) SetNillableHandledAt(v *time.Time) *DuplicateCandidateUpdateOne {
	if v != nil {
		_u.SetHandledAt(*v)
	}
	return _u
}

// ClearHandledAt clears the value of the "handled_at" field.
func (_u *DuplicateCandidateUpdateOne) ClearHandledAt() *DuplicateCandidateUpdateOne {
	_u.mutation.ClearHandledAt()
	return _u
}

// Mutation returns the DuplicateCandidateMutation object of the builder.
func (_u *DuplicateCandidateUpdateOne) Mutation() *DuplicateCandidateMutation {
	return _u.mutation
}

// Where appends a list predicates to the DuplicateCandidateUpdate builder.
func (_u *DuplicateCandidateUpdateOne) Where(ps ...predicate.DuplicateCandidate) *DuplicateCandidateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DuplicateCandidateUpdateOne) Select(field string, fields ...string) *DuplicateCandidateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DuplicateCandidate entity.
func (_u *DuplicateCandidateUpdateOne) Save(ctx context.Context) (*DuplicateCandidate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DuplicateCandidateUpdateOne) SaveX(ctx context.Context) *DuplicateCandidate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DuplicateCandidateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DuplicateCandidateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DuplicateCandidateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := duplicatecandidate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DuplicateCandidateUpdateOne) check() error {
	if v, ok := _u.mutation.DistanceM(); ok {
		if err := duplicatecandidate.DistanceMValidator(v); err != nil {
			return &ValidationError{Name: "distance_m", err: fmt.Errorf(`ent: validator failed for field "DuplicateCandidate.distance_m": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := duplicatecandidate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DuplicateCandidate.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DuplicateCandidateUpdateOne) sqlSave(ctx context.Context) (_node *DuplicateCandidate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(duplicatecandidate.Table, duplicatecandidate.Columns, sqlgraph.NewFieldSpec(duplicatecandidate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DuplicateCandidate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, duplicatecandidate.FieldID)
		for _, f := range fields {
			if !duplicatecandidate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != duplicatecandidate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(duplicatecandidate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DistanceM(); ok {
		_spec.SetField(duplicatecandidate.FieldDistanceM, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDistanceM(); ok {
		_spec.AddField(duplicatecandidate.FieldDistanceM, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PhotoBits(); ok {
		_spec.SetField(duplicatecandidate.FieldPhotoBits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPhotoBits(); ok {
		_spec.AddField(duplicatecandidate.FieldPhotoBits, field.TypeInt, value)
	}
	if _u.mutation.PhotoBitsCleared() {
		_spec.ClearField(duplicatecandidate.FieldPhotoBits, field.TypeInt)
	}
	if value, ok := _u.mutation.TextSimilarity(); ok {
		_spec.SetField(duplicatecandidate.FieldTextSimilarity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTextSimilarity(); ok {
		_spec.AddField(duplicatecandidate.FieldTextSimilarity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(duplicatecandidate.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(duplicatecandidate.FieldScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(duplicatecandidate.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.HandledBy(); ok {
		_spec.SetField(duplicatecandidate.FieldHandledBy, field.TypeUUID, value)
	}
	if _u.mutation.HandledByCleared() {
		_spec.ClearField(duplicatecandidate.FieldHandledBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.HandledAt(); ok {
		_spec.SetField(duplicatecandidate.FieldHandledAt, field.TypeTime, value)
	}
	if _u.mutation.HandledAtCleared() {
		_spec.ClearField(duplicatecandidate.FieldHandledAt, field.TypeTime)
	}
	_node = &DuplicateCandidate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{duplicatecandidate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
