// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"rentmapgh/internal/ent/listing"
	"rentmapgh/internal/ent/listingmedia"
	"rentmapgh/internal/ent/listingterms"
	"rentmapgh/internal/ent/predicate"
	"rentmapgh/internal/ent/unit"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ListingQuery is the builder for querying Listing entities.
type ListingQuery struct {
	config
	ctx        *QueryContext
	order      []listing.OrderOption
	inters     []Interceptor
	predicates []predicate.Listing
	withUnit   *UnitQuery
	withTerms  *ListingTermsQuery
	withMedia  *ListingMediaQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ListingQuery builder.
func (_q *ListingQuery) Where(ps ...predicate.Listing) *ListingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ListingQuery) Limit(limit int) *ListingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ListingQuery) Offset(offset int) *ListingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ListingQuery) Unique(unique bool) *ListingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ListingQuery) Order(o ...listing.OrderOption) *ListingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUnit chains the current query on the "unit" edge.
func (_q *ListingQuery) QueryUnit() *UnitQuery {
	query := (&UnitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(listing.Table, listing.FieldID, selector),
			sqlgraph.To(unit.Table, unit.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, listing.UnitTable, listing.UnitColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTerms chains the current query on the "terms" edge.
func (_q *ListingQuery) QueryTerms() *ListingTermsQuery {
	query := (&ListingTermsClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(listing.Table, listing.FieldID, selector),
			sqlgraph.To(listingterms.Table, listingterms.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, listing.TermsTable, listing.TermsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMedia chains the current query on the "media" edge.
func (_q *ListingQuery) QueryMedia() *ListingMediaQuery {
	query := (&ListingMediaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(listing.Table, listing.FieldID, selector),
			sqlgraph.To(listingmedia.Table, listingmedia.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, listing.MediaTable, listing.MediaColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Listing entity from the query.
// Returns a *NotFoundError when no Listing was found.
func (_q *ListingQuery) First(ctx context.Context) (*Listing, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{listing.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ListingQuery) FirstX(ctx context.Context) *Listing {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Listing ID from the query.
// Returns a *NotFoundError when no Listing ID was found.
func (_q *ListingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{listing.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ListingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Listing entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Listing entity is found.
// Returns a *NotFoundError when no Listing entities are found.
func (_q *ListingQuery) Only(ctx context.Context) (*Listing, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{listing.Label}
	default:
		return nil, &NotSingularError{listing.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ListingQuery) OnlyX(ctx context.Context) *Listing {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Listing ID in the query.
// Returns a *NotSingularError when more than one Listing ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ListingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{listing.Label}
	default:
		err = &NotSingularError{listing.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ListingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Listings.
func (_q *ListingQuery) All(ctx context.Context) ([]*Listing, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Listing, *ListingQuery]()
	return withInterceptors[[]*Listing](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ListingQuery) AllX(ctx context.Context) []*Listing {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Listing IDs.
func (_q *ListingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(listing.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ListingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ListingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ListingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ListingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ListingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ListingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ListingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ListingQuery) Clone() *ListingQuery {
	if _q == nil {
		return nil
	}
	return &ListingQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]listing.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Listing{}, _q.predicates...),
		withUnit:   _q.withUnit.Clone(),
		withTerms:  _q.withTerms.Clone(),
		withMedia:  _q.withMedia.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUnit tells the query-builder to eager-load the nodes that are connected to
// the "unit" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ListingQuery) WithUnit(opts ...func(*UnitQuery)) *ListingQuery {
	query := (&UnitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUnit = query
	return _q
}

// WithTerms tells the query-builder to eager-load the nodes that are connected to
// the "terms" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ListingQuery) WithTerms(opts ...func(*ListingTermsQuery)) *ListingQuery {
	query := (&ListingTermsClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTerms = query
	return _q
}

// WithMedia tells the query-builder to eager-load the nodes that are connected to
// the "media" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ListingQuery) WithMedia(opts ...func(*ListingMediaQuery)) *ListingQuery {
	query := (&ListingMediaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMedia = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Listing.Query().
//		GroupBy(listing.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ListingQuery) GroupBy(field string, fields ...string) *ListingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ListingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = listing.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Listing.Query().
//		Select(listing.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *ListingQuery) Select(fields ...string) *ListingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ListingSelect{ListingQuery: _q}
	sbuild.label = listing.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ListingSelect configured with the given aggregations.
func (_q *ListingQuery) Aggregate(fns ...AggregateFunc) *ListingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ListingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !listing.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ListingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Listing, error) {
	var (
		nodes       = []*Listing{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUnit != nil,
			_q.withTerms != nil,
			_q.withMedia != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Listing).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Listing{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUnit; query != nil {
		if err := _q.loadUnit(ctx, query, nodes, nil,
			func(n *Listing, e *Unit) { n.Edges.Unit = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTerms; query != nil {
		if err := _q.loadTerms(ctx, query, nodes, nil,
			func(n *Listing, e *ListingTerms) { n.Edges.Terms = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMedia; query != nil {
		if err := _q.loadMedia(ctx, query, nodes,
			func(n *Listing) { n.Edges.Media = []*ListingMedia{} },
			func(n *Listing, e *ListingMedia) { n.Edges.Media = append(n.Edges.Media, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ListingQuery) loadUnit(ctx context.Context, query *UnitQuery, nodes []*Listing, init func(*Listing), assign func(*Listing, *Unit)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Listing)
	for i := range nodes {
		fk := nodes[i].UnitID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(unit.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "unit_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ListingQuery) loadTerms(ctx context.Context, query *ListingTermsQuery, nodes []*Listing, init func(*Listing), assign func(*Listing, *ListingTerms)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Listing)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(listingterms.FieldListingID)
	}
	query.Where(predicate.ListingTerms(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(listing.TermsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ListingID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "listing_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ListingQuery) loadMedia(ctx context.Context, query *ListingMediaQuery, nodes []*Listing, init func(*Listing), assign func(*Listing, *ListingMedia)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Listing)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(listingmedia.FieldListingID)
	}
	query.Where(predicate.ListingMedia(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(listing.MediaColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ListingID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "listing_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ListingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ListingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(listing.Table, listing.Columns, sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, listing.FieldID)
		for i := range fields {
			if fields[i] != listing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUnit != nil {
			_spec.Node.AddColumnOnce(listing.FieldUnitID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ListingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(listing.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = listing.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ListingGroupBy is the group-by builder for Listing entities.
type ListingGroupBy struct {
	selector
	build *ListingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ListingGroupBy) Aggregate(fns ...AggregateFunc) *ListingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ListingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ListingQuery, *ListingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ListingGroupBy) sqlScan(ctx context.Context, root *ListingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ListingSelect is the builder for selecting fields of Listing entities.
type ListingSelect struct {
	*ListingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ListingSelect) Aggregate(fns ...AggregateFunc) *ListingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ListingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ListingQuery, *ListingSelect](ctx, _s.ListingQuery, _s, _s.inters, v)
}

func (_s *ListingSelect) sqlScan(ctx context.Context, root *ListingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
