// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"rentmapgh/internal/ent/predicate"
	"rentmapgh/internal/ent/savedlisting"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SavedListingDelete is the builder for deleting a SavedListing entity.
type SavedListingDelete struct {
	config
	hooks    []Hook
	mutation *SavedListingMutation
}

// Where appends a list predicates to the SavedListingDelete builder.
func (_d *SavedListingDelete) Where(ps ...predicate.SavedListing) *SavedListingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SavedListingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SavedListingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SavedListingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(savedlisting.Table, sqlgraph.NewFieldSpec(savedlisting.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SavedListingDeleteOne is the builder for deleting a single SavedListing entity.
type SavedListingDeleteOne struct {
	_d *SavedListingDelete
}

// Where appends a list predicates to the SavedListingDelete builder.
func (_d *SavedListingDeleteOne) Where(ps ...predicate.SavedListing) *SavedListingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SavedListingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{savedlisting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SavedListingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
