// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentmapgh/internal/ent/verification"
	"rentmapgh/internal/ent/verificationfile"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// VerificationFileCreate is the builder for creating a VerificationFile entity.
type VerificationFileCreate struct {
	config
	mutation *VerificationFileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *VerificationFileCreate) SetCreatedAt(v time.Time) *VerificationFileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VerificationFileCreate) SetNillableCreatedAt(v *time.Time) *VerificationFileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VerificationFileCreate) SetUpdatedAt(v time.Time) *VerificationFileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VerificationFileCreate) SetNillableUpdatedAt(v *time.Time) *VerificationFileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetVerificationID sets the "verification_id" field.
func (_c *VerificationFileCreate) SetVerificationID(v uuid.UUID) *VerificationFileCreate {
	_c.mutation.SetVerificationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VerificationFileCreate) SetUserID(v uuid.UUID) *VerificationFileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *VerificationFileCreate) SetKind(v verificationfile.Kind) *VerificationFileCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *VerificationFileCreate) SetStorageKey(v string) *VerificationFileCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *VerificationFileCreate) SetContentType(v string) *VerificationFileCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *VerificationFileCreate) SetSize(v int) *VerificationFileCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *VerificationFileCreate) SetSha256(v []byte) *VerificationFileCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetID sets the "id" field.
func (_c *VerificationFileCreate) SetID(v uuid.UUID) *VerificationFileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VerificationFileCreate) SetNillableID(v *uuid.UUID) *VerificationFileCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVerification sets the "verification" edge to the Verification entity.
func (_c *VerificationFileCreate) SetVerification(v *Verification) *VerificationFileCreate {
	return _c.SetVerificationID(v.ID)
}

// Mutation returns the VerificationFileMutation object of the builder.
func (_c *VerificationFileCreate) Mutation() *VerificationFileMutation {
	return _c.mutation
}

// Save creates the VerificationFile in the database.
func (_c *VerificationFileCreate) Save(ctx context.Context) (*VerificationFile, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VerificationFileCreate) SaveX(ctx context.Context) *VerificationFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VerificationFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VerificationFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VerificationFileCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if verificationfile.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized verificationfile.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := verificationfile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if verificationfile.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized verificationfile.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := verificationfile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if verificationfile.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized verificationfile.DefaultID (forgotten import ent/runtime?)")
		}
		v := verificationfile.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *VerificationFileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VerificationFile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VerificationFile.updated_at"`)}
	}
	if _, ok := _c.mutation.VerificationID(); !ok {
		return &ValidationError{Name: "verification_id", err: errors.New(`ent: missing required field "VerificationFile.verification_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VerificationFile.user_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "VerificationFile.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := verificationfile.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "VerificationFile.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "VerificationFile.storage_key"`)}
	}
	if v, ok := _c.mutation.StorageKey(); ok {
		if err := verificationfile.StorageKeyValidator(v); err != nil {
			return &ValidationError{Name: "storage_key", err: fmt.Errorf(`ent: validator failed for field "VerificationFile.storage_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "VerificationFile.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := verificationfile.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "VerificationFile.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "VerificationFile.size"`)}
	}
	if v, ok := _c.mutation.Size(); ok {
		if err := verificationfile.SizeValidator(v); err != nil {
			return &ValidationError{Name: "size", err: fmt.Errorf(`ent: validator failed for field "VerificationFile.size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "VerificationFile.sha256"`)}
	}
	if len(_c.mutation.VerificationIDs()) == 0 {
		return &ValidationError{Name: "verification", err: errors.New(`ent: missing required edge "VerificationFile.verification"`)}
	}
	return nil
}

func (_c *VerificationFileCreate) sqlSave(ctx context.Context) (*VerificationFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VerificationFileCreate) createSpec() (*VerificationFile, *sqlgraph.CreateSpec) {
	var (
		_node = &VerificationFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(verificationfile.Table, sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(verificationfile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(verificationfile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(verificationfile.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(verificationfile.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(verificationfile.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(verificationfile.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(verificationfile.FieldSize, field.TypeInt, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(verificationfile.FieldSha256, field.TypeBytes, value)
		_node.Sha256 = value
	}
	if nodes := _c.mutation.VerificationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   verificationfile.VerificationTable,
			Columns: []string{verificationfile.VerificationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verification.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VerificationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VerificationFile.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VerificationFileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VerificationFileCreate) OnConflict(opts ...sql.ConflictOption) *VerificationFileUpsertOne {
	_c.conflict = opts
	return &VerificationFileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VerificationFile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VerificationFileCreate) OnConflictColumns(columns ...string) *VerificationFileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VerificationFileUpsertOne{
		create: _c,
	}
}

type (
	// VerificationFileUpsertOne is the builder for "upsert"-ing
	//  one VerificationFile node.
	VerificationFileUpsertOne struct {
		create *VerificationFileCreate
	}

	// VerificationFileUpsert is the "OnConflict" setter.
	VerificationFileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VerificationFileUpsert) SetUpdatedAt(v time.Time) *VerificationFileUpsert {
	u.Set(verificationfile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VerificationFileUpsert) UpdateUpdatedAt() *VerificationFileUpsert {
	u.SetExcluded(verificationfile.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.VerificationFile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(verificationfile.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VerificationFileUpsertOne) UpdateNewValues() *VerificationFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(verificationfile.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(verificationfile.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.VerificationID(); exists {
			s.SetIgnore(verificationfile.FieldVerificationID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(verificationfile.FieldUserID)
		}
		if _, exists := u.create.mutation.Kind(); exists {
			s.SetIgnore(verificationfile.FieldKind)
		}
		if _, exists := u.create.mutation.StorageKey(); exists {
			s.SetIgnore(verificationfile.FieldStorageKey)
		}
		if _, exists := u.create.mutation.ContentType(); exists {
			s.SetIgnore(verificationfile.FieldContentType)
		}
		if _, exists := u.create.mutation.Size(); exists {
			s.SetIgnore(verificationfile.FieldSize)
		}
		if _, exists := u.create.mutation.Sha256(); exists {
			s.SetIgnore(verificationfile.FieldSha256)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VerificationFile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VerificationFileUpsertOne) Ignore() *VerificationFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VerificationFileUpsertOne) DoNothing() *VerificationFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VerificationFileCreate.OnConflict
// documentation for more info.
func (u *VerificationFileUpsertOne) Update(set func(*VerificationFileUpsert)) *VerificationFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VerificationFileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VerificationFileUpsertOne) SetUpdatedAt(v time.Time) *VerificationFileUpsertOne {
	return u.Update(func(s *VerificationFileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VerificationFileUpsertOne) UpdateUpdatedAt() *VerificationFileUpsertOne {
	return u.Update(func(s *VerificationFileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VerificationFileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VerificationFileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VerificationFileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VerificationFileUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: VerificationFileUpsertOne.ID is not supported by MySQL driver. Use VerificationFileUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VerificationFileUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VerificationFileCreateBulk is the builder for creating many VerificationFile entities in bulk.
type VerificationFileCreateBulk struct {
	config
	err      error
	builders []*VerificationFileCreate
	conflict []sql.ConflictOption
}

// Save creates the VerificationFile entities in the database.
func (_c *VerificationFileCreateBulk) Save(ctx context.Context) ([]*VerificationFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VerificationFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VerificationFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VerificationFileCreateBulk) SaveX(ctx context.Context) []*VerificationFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VerificationFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VerificationFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VerificationFile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VerificationFileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VerificationFileCreateBulk) OnConflict(opts ...sql.ConflictOption) *VerificationFileUpsertBulk {
	_c.conflict = opts
	return &VerificationFileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VerificationFile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VerificationFileCreateBulk) OnConflictColumns(columns ...string) *VerificationFileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VerificationFileUpsertBulk{
		create: _c,
	}
}

// VerificationFileUpsertBulk is the builder for "upsert"-ing
// a bulk of VerificationFile nodes.
type VerificationFileUpsertBulk struct {
	create *VerificationFileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VerificationFile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(verificationfile.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VerificationFileUpsertBulk) UpdateNewValues() *VerificationFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(verificationfile.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(verificationfile.FieldCreatedAt)
			}
			if _, exists := b.mutation.VerificationID(); exists {
				s.SetIgnore(verificationfile.FieldVerificationID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(verificationfile.FieldUserID)
			}
			if _, exists := b.mutation.Kind(); exists {
				s.SetIgnore(verificationfile.FieldKind)
			}
			if _, exists := b.mutation.StorageKey(); exists {
				s.SetIgnore(verificationfile.FieldStorageKey)
			}
			if _, exists := b.mutation.ContentType(); exists {
				s.SetIgnore(verificationfile.FieldContentType)
			}
			if _, exists := b.mutation.Size(); exists {
				s.SetIgnore(verificationfile.FieldSize)
			}
			if _, exists := b.mutation.Sha256(); exists {
				s.SetIgnore(verificationfile.FieldSha256)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VerificationFile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VerificationFileUpsertBulk) Ignore() *VerificationFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VerificationFileUpsertBulk) DoNothing() *VerificationFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VerificationFileCreateBulk.OnConflict
// documentation for more info.
func (u *VerificationFileUpsertBulk) Update(set func(*VerificationFileUpsert)) *VerificationFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VerificationFileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VerificationFileUpsertBulk) SetUpdatedAt(v time.Time) *VerificationFileUpsertBulk {
	return u.Update(func(s *VerificationFileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VerificationFileUpsertBulk) UpdateUpdatedAt() *VerificationFileUpsertBulk {
	return u.Update(func(s *VerificationFileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VerificationFileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VerificationFileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VerificationFileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VerificationFileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
