// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentmapgh/internal/ent/predicate"
	"rentmapgh/internal/ent/verificationfile"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VerificationFileUpdate is the builder for updating VerificationFile entities.
type VerificationFileUpdate struct {
	config
	hooks    []Hook
	mutation *VerificationFileMutation
}

// Where appends a list predicates to the VerificationFileUpdate builder.
func (_u *VerificationFileUpdate) Where(ps ...predicate.VerificationFile) *VerificationFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VerificationFileUpdate) SetUpdatedAt(v time.Time) *VerificationFileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VerificationFileMutation object of the builder.
func (_u *VerificationFileUpdate) Mutation() *VerificationFileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VerificationFileUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VerificationFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VerificationFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VerificationFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VerificationFileUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if verificationfile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized verificationfile.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := verificationfile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *VerificationFileUpdate) check() error {
	if _u.mutation.VerificationCleared() && len(_u.mutation.VerificationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VerificationFile.verification"`)
	}
	return nil
}

func (_u *VerificationFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(verificationfile.Table, verificationfile.Columns, sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(verificationfile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verificationfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VerificationFileUpdateOne is the builder for updating a single VerificationFile entity.
type VerificationFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VerificationFileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VerificationFileUpdateOne) SetUpdatedAt(v time.Time) *VerificationFileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the VerificationFileMutation object of the builder.
func (_u *VerificationFileUpdateOne) Mutation() *VerificationFileMutation {
	return _u.mutation
}

// Where appends a list predicates to the VerificationFileUpdate builder.
func (_u *VerificationFileUpdateOne) Where(ps ...predicate.VerificationFile) *VerificationFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VerificationFileUpdateOne) Select(field string, fields ...string) *VerificationFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VerificationFile entity.
func (_u *VerificationFileUpdateOne) Save(ctx context.Context) (*VerificationFile, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VerificationFileUpdateOne) SaveX(ctx context.Context) *VerificationFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VerificationFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VerificationFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VerificationFileUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if verificationfile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized verificationfile.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := verificationfile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *VerificationFileUpdateOne) check() error {
	if _u.mutation.VerificationCleared() && len(_u.mutation.VerificationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VerificationFile.verification"`)
	}
	return nil
}

func (_u *VerificationFileUpdateOne) sqlSave(ctx context.Context) (_node *VerificationFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(verificationfile.Table, verificationfile.Columns, sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VerificationFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, verificationfile.FieldID)
		for _, f := range fields {
			if !verificationfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != verificationfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(verificationfile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &VerificationFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verificationfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
