// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rentmapgh/internal/ent/predicate"
	"rentmapgh/internal/ent/verification"
	"rentmapgh/internal/ent/verificationfile"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// VerificationUpdate is the builder for updating Verification entities.
type VerificationUpdate struct {
	config
	hooks    []Hook
	mutation *VerificationMutation
}

// Where appends a list predicates to the VerificationUpdate builder.
func (_u *VerificationUpdate) Where(ps ...predicate.Verification) *VerificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VerificationUpdate) SetUpdatedAt(v time.Time) *VerificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *VerificationUpdate) SetStatus(v verification.Status) *VerificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableStatus(v *verification.Status) *VerificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *VerificationUpdate) SetMethod(v string) *VerificationUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableMethod(v *string) *VerificationUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetIDNumberEnc sets the "id_number_enc" field.
func (_u *VerificationUpdate) SetIDNumberEnc(v []byte) *VerificationUpdate {
	_u.mutation.SetIDNumberEnc(v)
	return _u
}

// ClearIDNumberEnc clears the value of the "id_number_enc" field.
func (_u *VerificationUpdate) ClearIDNumberEnc() *VerificationUpdate {
	_u.mutation.ClearIDNumberEnc()
	return _u
}

// SetIDNumberLast4 sets the "id_number_last4" field.
func (_u *VerificationUpdate) SetIDNumberLast4(v string) *VerificationUpdate {
	_u.mutation.SetIDNumberLast4(v)
	return _u
}

// SetNillableIDNumberLast4 sets the "id_number_last4" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableIDNumberLast4(v *string) *VerificationUpdate {
	if v != nil {
		_u.SetIDNumberLast4(*v)
	}
	return _u
}

// ClearIDNumberLast4 clears the value of the "id_number_last4" field.
func (_u *VerificationUpdate) ClearIDNumberLast4() *VerificationUpdate {
	_u.mutation.ClearIDNumberLast4()
	return _u
}

// SetLicenseNumber sets the "license_number" field.
func (_u *VerificationUpdate) SetLicenseNumber(v string) *VerificationUpdate {
	_u.mutation.SetLicenseNumber(v)
	return _u
}

// SetNillableLicenseNumber sets the "license_number" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableLicenseNumber(v *string) *VerificationUpdate {
	if v != nil {
		_u.SetLicenseNumber(*v)
	}
	return _u
}

// ClearLicenseNumber clears the value of the "license_number" field.
func (_u *VerificationUpdate) ClearLicenseNumber() *VerificationUpdate {
	_u.mutation.ClearLicenseNumber()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *VerificationUpdate) SetReviewedBy(v uuid.UUID) *VerificationUpdate {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableReviewedBy(v *uuid.UUID) *VerificationUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *VerificationUpdate) ClearReviewedBy() *VerificationUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *VerificationUpdate) SetReviewedAt(v time.Time) *VerificationUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableReviewedAt(v *time.Time) *VerificationUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *VerificationUpdate) ClearReviewedAt() *VerificationUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetDecisionReason sets the "decision_reason" field.
func (_u *VerificationUpdate) SetDecisionReason(v string) *VerificationUpdate {
	_u.mutation.SetDecisionReason(v)
	return _u
}

// SetNillableDecisionReason sets the "decision_reason" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableDecisionReason(v *string) *VerificationUpdate {
	if v != nil {
		_u.SetDecisionReason(*v)
	}
	return _u
}

// ClearDecisionReason clears the value of the "decision_reason" field.
func (_u *VerificationUpdate) ClearDecisionReason() *VerificationUpdate {
	_u.mutation.ClearDecisionReason()
	return _u
}

// SetDecisionNote sets the "decision_note" field.
func (_u *VerificationUpdate) SetDecisionNote(v string) *VerificationUpdate {
	_u.mutation.SetDecisionNote(v)
	return _u
}

// SetNillableDecisionNote sets the "decision_note" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableDecisionNote(v *string) *VerificationUpdate {
	if v != nil {
		_u.SetDecisionNote(*v)
	}
	return _u
}

// ClearDecisionNote clears the value of the "decision_note" field.
func (_u *VerificationUpdate) ClearDecisionNote() *VerificationUpdate {
	_u.mutation.ClearDecisionNote()
	return _u
}

// SetEvidencePurgedAt sets the "evidence_purged_at" field.
func (_u *VerificationUpdate) SetEvidencePurgedAt(v time.Time) *VerificationUpdate {
	_u.mutation.SetEvidencePurgedAt(v)
	return _u
}

// SetNillableEvidencePurgedAt sets the "evidence_purged_at" field if the given value is not nil.
func (_u *VerificationUpdate) SetNillableEvidencePurgedAt(v *time.Time) *VerificationUpdate {
	if v != nil {
		_u.SetEvidencePurgedAt(*v)
	}
	return _u
}

// ClearEvidencePurgedAt clears the value of the "evidence_purged_at" field.
func (_u *VerificationUpdate) ClearEvidencePurgedAt() *VerificationUpdate {
	_u.mutation.ClearEvidencePurgedAt()
	return _u
}

// AddFileIDs adds the "files" edge to the VerificationFile entity by IDs.
func (_u *VerificationUpdate) AddFileIDs(ids ...uuid.UUID) *VerificationUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the VerificationFile entity.
func (_u *VerificationUpdate) AddFiles(v ...*VerificationFile) *VerificationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the VerificationMutation object of the builder.
func (_u *VerificationUpdate) Mutation() *VerificationMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the VerificationFile entity.
func (_u *VerificationUpdate) ClearFiles() *VerificationUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to VerificationFile entities by IDs.
func (_u *VerificationUpdate) RemoveFileIDs(ids ...uuid.UUID) *VerificationUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to VerificationFile entities.
func (_u *VerificationUpdate) RemoveFiles(v ...*VerificationFile) *VerificationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VerificationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VerificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VerificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VerificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VerificationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if verification.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized verification.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := verification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *VerificationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := verification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Verification.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := verification.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Verification.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IDNumberLast4(); ok {
		if err := verification.IDNumberLast4Validator(v); err != nil {
			return &ValidationError{Name: "id_number_last4", err: fmt.Errorf(`ent: validator failed for field "Verification.id_number_last4": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LicenseNumber(); ok {
		if err := verification.LicenseNumberValidator(v); err != nil {
			return &ValidationError{Name: "license_number", err: fmt.Errorf(`ent: validator failed for field "Verification.license_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DecisionReason(); ok {
		if err := verification.DecisionReasonValidator(v); err != nil {
			return &ValidationError{Name: "decision_reason", err: fmt.Errorf(`ent: validator failed for field "Verification.decision_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DecisionNote(); ok {
		if err := verification.DecisionNoteValidator(v); err != nil {
			return &ValidationError{Name: "decision_note", err: fmt.Errorf(`ent: validator failed for field "Verification.decision_note": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Verification.user"`)
	}
	return nil
}

func (_u *VerificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(verification.Table, verification.Columns, sqlgraph.NewFieldSpec(verification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(verification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(verification.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(verification.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.IDNumberEnc(); ok {
		_spec.SetField(verification.FieldIDNumberEnc, field.TypeBytes, value)
	}
	if _u.mutation.IDNumberEncCleared() {
		_spec.ClearField(verification.FieldIDNumberEnc, field.TypeBytes)
	}
	if value, ok := _u.mutation.IDNumberLast4(); ok {
		_spec.SetField(verification.FieldIDNumberLast4, field.TypeString, value)
	}
	if _u.mutation.IDNumberLast4Cleared() {
		_spec.ClearField(verification.FieldIDNumberLast4, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseNumber(); ok {
		_spec.SetField(verification.FieldLicenseNumber, field.TypeString, value)
	}
	if _u.mutation.LicenseNumberCleared() {
		_spec.ClearField(verification.FieldLicenseNumber, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(verification.FieldReviewedBy, field.TypeUUID, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(verification.FieldReviewedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(verification.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(verification.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DecisionReason(); ok {
		_spec.SetField(verification.FieldDecisionReason, field.TypeString, value)
	}
	if _u.mutation.DecisionReasonCleared() {
		_spec.ClearField(verification.FieldDecisionReason, field.TypeString)
	}
	if value, ok := _u.mutation.DecisionNote(); ok {
		_spec.SetField(verification.FieldDecisionNote, field.TypeString, value)
	}
	if _u.mutation.DecisionNoteCleared() {
		_spec.ClearField(verification.FieldDecisionNote, field.TypeString)
	}
	if value, ok := _u.mutation.EvidencePurgedAt(); ok {
		_spec.SetField(verification.FieldEvidencePurgedAt, field.TypeTime, value)
	}
	if _u.mutation.EvidencePurgedAtCleared() {
		_spec.ClearField(verification.FieldEvidencePurgedAt, field.TypeTime)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verification.FilesTable,
			Columns: []string{verification.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verification.FilesTable,
			Columns: []string{verification.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verification.FilesTable,
			Columns: []string{verification.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VerificationUpdateOne is the builder for updating a single Verification entity.
type VerificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VerificationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VerificationUpdateOne) SetUpdatedAt(v time.Time) *VerificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *VerificationUpdateOne) SetStatus(v verification.Status) *VerificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableStatus(v *verification.Status) *VerificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *VerificationUpdateOne) SetMethod(v string) *VerificationUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableMethod(v *string) *VerificationUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetIDNumberEnc sets the "id_number_enc" field.
func (_u *VerificationUpdateOne) SetIDNumberEnc(v []byte) *VerificationUpdateOne {
	_u.mutation.SetIDNumberEnc(v)
	return _u
}

// ClearIDNumberEnc clears the value of the "id_number_enc" field.
func (_u *VerificationUpdateOne) ClearIDNumberEnc() *VerificationUpdateOne {
	_u.mutation.ClearIDNumberEnc()
	return _u
}

// SetIDNumberLast4 sets the "id_number_last4" field.
func (_u *VerificationUpdateOne) SetIDNumberLast4(v string) *VerificationUpdateOne {
	_u.mutation.SetIDNumberLast4(v)
	return _u
}

// SetNillableIDNumberLast4 sets the "id_number_last4" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableIDNumberLast4(v *string) *VerificationUpdateOne {
	if v != nil {
		_u.SetIDNumberLast4(*v)
	}
	return _u
}

// ClearIDNumberLast4 clears the value of the "id_number_last4" field.
func (_u *VerificationUpdateOne) ClearIDNumberLast4() *VerificationUpdateOne {
	_u.mutation.ClearIDNumberLast4()
	return _u
}

// SetLicenseNumber sets the "license_number" field.
func (_u *VerificationUpdateOne) SetLicenseNumber(v string) *VerificationUpdateOne {
	_u.mutation.SetLicenseNumber(v)
	return _u
}

// SetNillableLicenseNumber sets the "license_number" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableLicenseNumber(v *string) *VerificationUpdateOne {
	if v != nil {
		_u.SetLicenseNumber(*v)
	}
	return _u
}

// ClearLicenseNumber clears the value of the "license_number" field.
func (_u *VerificationUpdateOne) ClearLicenseNumber() *VerificationUpdateOne {
	_u.mutation.ClearLicenseNumber()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *VerificationUpdateOne) SetReviewedBy(v uuid.UUID) *VerificationUpdateOne {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableReviewedBy(v *uuid.UUID) *VerificationUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *VerificationUpdateOne) ClearReviewedBy() *VerificationUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *VerificationUpdateOne) SetReviewedAt(v time.Time) *VerificationUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableReviewedAt(v *time.Time) *VerificationUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *VerificationUpdateOne) ClearReviewedAt() *VerificationUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetDecisionReason sets the "decision_reason" field.
func (_u *VerificationUpdateOne) SetDecisionReason(v string) *VerificationUpdateOne {
	_u.mutation.SetDecisionReason(v)
	return _u
}

// SetNillableDecisionReason sets the "decision_reason" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableDecisionReason(v *string) *VerificationUpdateOne {
	if v != nil {
		_u.SetDecisionReason(*v)
	}
	return _u
}

// ClearDecisionReason clears the value of the "decision_reason" field.
func (_u *VerificationUpdateOne) ClearDecisionReason() *VerificationUpdateOne {
	_u.mutation.ClearDecisionReason()
	return _u
}

// SetDecisionNote sets the "decision_note" field.
func (_u *VerificationUpdateOne) SetDecisionNote(v string) *VerificationUpdateOne {
	_u.mutation.SetDecisionNote(v)
	return _u
}

// SetNillableDecisionNote sets the "decision_note" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableDecisionNote(v *string) *VerificationUpdateOne {
	if v != nil {
		_u.SetDecisionNote(*v)
	}
	return _u
}

// ClearDecisionNote clears the value of the "decision_note" field.
func (_u *VerificationUpdateOne) ClearDecisionNote() *VerificationUpdateOne {
	_u.mutation.ClearDecisionNote()
	return _u
}

// SetEvidencePurgedAt sets the "evidence_purged_at" field.
func (_u *VerificationUpdateOne) SetEvidencePurgedAt(v time.Time) *VerificationUpdateOne {
	_u.mutation.SetEvidencePurgedAt(v)
	return _u
}

// SetNillableEvidencePurgedAt sets the "evidence_purged_at" field if the given value is not nil.
func (_u *VerificationUpdateOne) SetNillableEvidencePurgedAt(v *time.Time) *VerificationUpdateOne {
	if v != nil {
		_u.SetEvidencePurgedAt(*v)
	}
	return _u
}

// ClearEvidencePurgedAt clears the value of the "evidence_purged_at" field.
func (_u *VerificationUpdateOne) ClearEvidencePurgedAt() *VerificationUpdateOne {
	_u.mutation.ClearEvidencePurgedAt()
	return _u
}

// AddFileIDs adds the "files" edge to the VerificationFile entity by IDs.
func (_u *VerificationUpdateOne) AddFileIDs(ids ...uuid.UUID) *VerificationUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the VerificationFile entity.
func (_u *VerificationUpdateOne) AddFiles(v ...*VerificationFile) *VerificationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the VerificationMutation object of the builder.
func (_u *VerificationUpdateOne) Mutation() *VerificationMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the VerificationFile entity.
func (_u *VerificationUpdateOne) ClearFiles() *VerificationUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to VerificationFile entities by IDs.
func (_u *VerificationUpdateOne) RemoveFileIDs(ids ...uuid.UUID) *VerificationUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to VerificationFile entities.
func (_u *VerificationUpdateOne) RemoveFiles(v ...*VerificationFile) *VerificationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the VerificationUpdate builder.
func (_u *VerificationUpdateOne) Where(ps ...predicate.Verification) *VerificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VerificationUpdateOne) Select(field string, fields ...string) *VerificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Verification entity.
func (_u *VerificationUpdateOne) Save(ctx context.Context) (*Verification, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VerificationUpdateOne) SaveX(ctx context.Context) *Verification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VerificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VerificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VerificationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if verification.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized verification.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := verification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *VerificationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := verification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Verification.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := verification.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "Verification.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IDNumberLast4(); ok {
		if err := verification.IDNumberLast4Validator(v); err != nil {
			return &ValidationError{Name: "id_number_last4", err: fmt.Errorf(`ent: validator failed for field "Verification.id_number_last4": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LicenseNumber(); ok {
		if err := verification.LicenseNumberValidator(v); err != nil {
			return &ValidationError{Name: "license_number", err: fmt.Errorf(`ent: validator failed for field "Verification.license_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DecisionReason(); ok {
		if err := verification.DecisionReasonValidator(v); err != nil {
			return &ValidationError{Name: "decision_reason", err: fmt.Errorf(`ent: validator failed for field "Verification.decision_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DecisionNote(); ok {
		if err := verification.DecisionNoteValidator(v); err != nil {
			return &ValidationError{Name: "decision_note", err: fmt.Errorf(`ent: validator failed for field "Verification.decision_note": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Verification.user"`)
	}
	return nil
}

func (_u *VerificationUpdateOne) sqlSave(ctx context.Context) (_node *Verification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(verification.Table, verification.Columns, sqlgraph.NewFieldSpec(verification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Verification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, verification.FieldID)
		for _, f := range fields {
			if !verification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != verification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(verification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(verification.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(verification.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.IDNumberEnc(); ok {
		_spec.SetField(verification.FieldIDNumberEnc, field.TypeBytes, value)
	}
	if _u.mutation.IDNumberEncCleared() {
		_spec.ClearField(verification.FieldIDNumberEnc, field.TypeBytes)
	}
	if value, ok := _u.mutation.IDNumberLast4(); ok {
		_spec.SetField(verification.FieldIDNumberLast4, field.TypeString, value)
	}
	if _u.mutation.IDNumberLast4Cleared() {
		_spec.ClearField(verification.FieldIDNumberLast4, field.TypeString)
	}
	if value, ok := _u.mutation.LicenseNumber(); ok {
		_spec.SetField(verification.FieldLicenseNumber, field.TypeString, value)
	}
	if _u.mutation.LicenseNumberCleared() {
		_spec.ClearField(verification.FieldLicenseNumber, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(verification.FieldReviewedBy, field.TypeUUID, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(verification.FieldReviewedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(verification.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(verification.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DecisionReason(); ok {
		_spec.SetField(verification.FieldDecisionReason, field.TypeString, value)
	}
	if _u.mutation.DecisionReasonCleared() {
		_spec.ClearField(verification.FieldDecisionReason, field.TypeString)
	}
	if value, ok := _u.mutation.DecisionNote(); ok {
		_spec.SetField(verification.FieldDecisionNote, field.TypeString, value)
	}
	if _u.mutation.DecisionNoteCleared() {
		_spec.ClearField(verification.FieldDecisionNote, field.TypeString)
	}
	if value, ok := _u.mutation.EvidencePurgedAt(); ok {
		_spec.SetField(verification.FieldEvidencePurgedAt, field.TypeTime, value)
	}
	if _u.mutation.EvidencePurgedAtCleared() {
		_spec.ClearField(verification.FieldEvidencePurgedAt, field.TypeTime)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verification.FilesTable,
			Columns: []string{verification.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verification.FilesTable,
			Columns: []string{verification.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   verification.FilesTable,
			Columns: []string{verification.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Verification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{verification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
