// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"rentmapgh/internal/ent/agentmandate"
	"rentmapgh/internal/ent/agentprofile"
	"rentmapgh/internal/ent/auditevent"
	"rentmapgh/internal/ent/landlordprofile"
	"rentmapgh/internal/ent/listing"
	"rentmapgh/internal/ent/listingmedia"
	"rentmapgh/internal/ent/listingterms"
	"rentmapgh/internal/ent/otpcode"
	"rentmapgh/internal/ent/property"
	"rentmapgh/internal/ent/roleassignment"
	"rentmapgh/internal/ent/savedlisting"
	"rentmapgh/internal/ent/schema"
	"rentmapgh/internal/ent/session"
	"rentmapgh/internal/ent/unit"
	"rentmapgh/internal/ent/user"
	"rentmapgh/internal/ent/verification"
	"rentmapgh/internal/ent/verificationfile"
	"rentmapgh/internal/ent/viewing"
	"rentmapgh/internal/ent/waitlistentry"
	"time"

	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentmandateMixin := schema.AgentMandate{}.Mixin()
	agentmandateMixinFields0 := agentmandateMixin[0].Fields()
	_ = agentmandateMixinFields0
	agentmandateMixinFields1 := agentmandateMixin[1].Fields()
	_ = agentmandateMixinFields1
	agentmandateFields := schema.AgentMandate{}.Fields()
	_ = agentmandateFields
	// agentmandateDescCreatedAt is the schema descriptor for created_at field.
	agentmandateDescCreatedAt := agentmandateMixinFields1[0].Descriptor()
	// agentmandate.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentmandate.DefaultCreatedAt = agentmandateDescCreatedAt.Default.(func() time.Time)
	// agentmandateDescUpdatedAt is the schema descriptor for updated_at field.
	agentmandateDescUpdatedAt := agentmandateMixinFields1[1].Descriptor()
	// agentmandate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentmandate.DefaultUpdatedAt = agentmandateDescUpdatedAt.Default.(func() time.Time)
	// agentmandate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentmandate.UpdateDefaultUpdatedAt = agentmandateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentmandateDescLandlordPhone is the schema descriptor for landlord_phone field.
	agentmandateDescLandlordPhone := agentmandateFields[2].Descriptor()
	// agentmandate.LandlordPhoneValidator is a validator for the "landlord_phone" field. It is called by the builders before save.
	agentmandate.LandlordPhoneValidator = func() func(string) error {
		validators := agentmandateDescLandlordPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(landlord_phone string) error {
			for _, fn := range fns {
				if err := fn(landlord_phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// agentmandateDescLandlordName is the schema descriptor for landlord_name field.
	agentmandateDescLandlordName := agentmandateFields[3].Descriptor()
	// agentmandate.LandlordNameValidator is a validator for the "landlord_name" field. It is called by the builders before save.
	agentmandate.LandlordNameValidator = agentmandateDescLandlordName.Validators[0].(func(string) error)
	// agentmandateDescMonths is the schema descriptor for months field.
	agentmandateDescMonths := agentmandateFields[6].Descriptor()
	// agentmandate.DefaultMonths holds the default value on creation for the months field.
	agentmandate.DefaultMonths = agentmandateDescMonths.Default.(int)
	// agentmandate.MonthsValidator is a validator for the "months" field. It is called by the builders before save.
	agentmandate.MonthsValidator = agentmandateDescMonths.Validators[0].(func(int) error)
	// agentmandateDescTokenHash is the schema descriptor for token_hash field.
	agentmandateDescTokenHash := agentmandateFields[7].Descriptor()
	// agentmandate.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	agentmandate.TokenHashValidator = agentmandateDescTokenHash.Validators[0].(func([]byte) error)
	// agentmandateDescSends is the schema descriptor for sends field.
	agentmandateDescSends := agentmandateFields[9].Descriptor()
	// agentmandate.DefaultSends holds the default value on creation for the sends field.
	agentmandate.DefaultSends = agentmandateDescSends.Default.(int)
	// agentmandate.SendsValidator is a validator for the "sends" field. It is called by the builders before save.
	agentmandate.SendsValidator = agentmandateDescSends.Validators[0].(func(int) error)
	// agentmandateDescReported is the schema descriptor for reported field.
	agentmandateDescReported := agentmandateFields[12].Descriptor()
	// agentmandate.DefaultReported holds the default value on creation for the reported field.
	agentmandate.DefaultReported = agentmandateDescReported.Default.(bool)
	// agentmandateDescID is the schema descriptor for id field.
	agentmandateDescID := agentmandateMixinFields0[0].Descriptor()
	// agentmandate.DefaultID holds the default value on creation for the id field.
	agentmandate.DefaultID = agentmandateDescID.Default.(func() uuid.UUID)
	agentprofileMixin := schema.AgentProfile{}.Mixin()
	agentprofileMixinFields0 := agentprofileMixin[0].Fields()
	_ = agentprofileMixinFields0
	agentprofileMixinFields1 := agentprofileMixin[1].Fields()
	_ = agentprofileMixinFields1
	agentprofileFields := schema.AgentProfile{}.Fields()
	_ = agentprofileFields
	// agentprofileDescCreatedAt is the schema descriptor for created_at field.
	agentprofileDescCreatedAt := agentprofileMixinFields1[0].Descriptor()
	// agentprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentprofile.DefaultCreatedAt = agentprofileDescCreatedAt.Default.(func() time.Time)
	// agentprofileDescUpdatedAt is the schema descriptor for updated_at field.
	agentprofileDescUpdatedAt := agentprofileMixinFields1[1].Descriptor()
	// agentprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agentprofile.DefaultUpdatedAt = agentprofileDescUpdatedAt.Default.(func() time.Time)
	// agentprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agentprofile.UpdateDefaultUpdatedAt = agentprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentprofileDescLicenseNumber is the schema descriptor for license_number field.
	agentprofileDescLicenseNumber := agentprofileFields[1].Descriptor()
	// agentprofile.LicenseNumberValidator is a validator for the "license_number" field. It is called by the builders before save.
	agentprofile.LicenseNumberValidator = agentprofileDescLicenseNumber.Validators[0].(func(string) error)
	// agentprofileDescAgencyName is the schema descriptor for agency_name field.
	agentprofileDescAgencyName := agentprofileFields[2].Descriptor()
	// agentprofile.AgencyNameValidator is a validator for the "agency_name" field. It is called by the builders before save.
	agentprofile.AgencyNameValidator = agentprofileDescAgencyName.Validators[0].(func(string) error)
	// agentprofileDescID is the schema descriptor for id field.
	agentprofileDescID := agentprofileMixinFields0[0].Descriptor()
	// agentprofile.DefaultID holds the default value on creation for the id field.
	agentprofile.DefaultID = agentprofileDescID.Default.(func() uuid.UUID)
	auditeventMixin := schema.AuditEvent{}.Mixin()
	auditeventMixinFields0 := auditeventMixin[0].Fields()
	_ = auditeventMixinFields0
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescAction is the schema descriptor for action field.
	auditeventDescAction := auditeventFields[2].Descriptor()
	// auditevent.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditevent.ActionValidator = func() func(string) error {
		validators := auditeventDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditeventDescTargetType is the schema descriptor for target_type field.
	auditeventDescTargetType := auditeventFields[3].Descriptor()
	// auditevent.TargetTypeValidator is a validator for the "target_type" field. It is called by the builders before save.
	auditevent.TargetTypeValidator = auditeventDescTargetType.Validators[0].(func(string) error)
	// auditeventDescTargetID is the schema descriptor for target_id field.
	auditeventDescTargetID := auditeventFields[4].Descriptor()
	// auditevent.TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	auditevent.TargetIDValidator = auditeventDescTargetID.Validators[0].(func(string) error)
	// auditeventDescIP is the schema descriptor for ip field.
	auditeventDescIP := auditeventFields[5].Descriptor()
	// auditevent.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	auditevent.IPValidator = auditeventDescIP.Validators[0].(func(string) error)
	// auditeventDescUserAgent is the schema descriptor for user_agent field.
	auditeventDescUserAgent := auditeventFields[6].Descriptor()
	// auditevent.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	auditevent.UserAgentValidator = auditeventDescUserAgent.Validators[0].(func(string) error)
	// auditeventDescID is the schema descriptor for id field.
	auditeventDescID := auditeventMixinFields0[0].Descriptor()
	// auditevent.DefaultID holds the default value on creation for the id field.
	auditevent.DefaultID = auditeventDescID.Default.(func() uuid.UUID)
	landlordprofileMixin := schema.LandlordProfile{}.Mixin()
	landlordprofileMixinFields0 := landlordprofileMixin[0].Fields()
	_ = landlordprofileMixinFields0
	landlordprofileMixinFields1 := landlordprofileMixin[1].Fields()
	_ = landlordprofileMixinFields1
	landlordprofileFields := schema.LandlordProfile{}.Fields()
	_ = landlordprofileFields
	// landlordprofileDescCreatedAt is the schema descriptor for created_at field.
	landlordprofileDescCreatedAt := landlordprofileMixinFields1[0].Descriptor()
	// landlordprofile.DefaultCreatedAt holds the default value on creation for the created_at field.
	landlordprofile.DefaultCreatedAt = landlordprofileDescCreatedAt.Default.(func() time.Time)
	// landlordprofileDescUpdatedAt is the schema descriptor for updated_at field.
	landlordprofileDescUpdatedAt := landlordprofileMixinFields1[1].Descriptor()
	// landlordprofile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	landlordprofile.DefaultUpdatedAt = landlordprofileDescUpdatedAt.Default.(func() time.Time)
	// landlordprofile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	landlordprofile.UpdateDefaultUpdatedAt = landlordprofileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// landlordprofileDescDisplayName is the schema descriptor for display_name field.
	landlordprofileDescDisplayName := landlordprofileFields[1].Descriptor()
	// landlordprofile.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	landlordprofile.DisplayNameValidator = landlordprofileDescDisplayName.Validators[0].(func(string) error)
	// landlordprofileDescBio is the schema descriptor for bio field.
	landlordprofileDescBio := landlordprofileFields[2].Descriptor()
	// landlordprofile.BioValidator is a validator for the "bio" field. It is called by the builders before save.
	landlordprofile.BioValidator = landlordprofileDescBio.Validators[0].(func(string) error)
	// landlordprofileDescID is the schema descriptor for id field.
	landlordprofileDescID := landlordprofileMixinFields0[0].Descriptor()
	// landlordprofile.DefaultID holds the default value on creation for the id field.
	landlordprofile.DefaultID = landlordprofileDescID.Default.(func() uuid.UUID)
	listingMixin := schema.Listing{}.Mixin()
	listingMixinFields0 := listingMixin[0].Fields()
	_ = listingMixinFields0
	listingMixinFields1 := listingMixin[1].Fields()
	_ = listingMixinFields1
	listingFields := schema.Listing{}.Fields()
	_ = listingFields
	// listingDescCreatedAt is the schema descriptor for created_at field.
	listingDescCreatedAt := listingMixinFields1[0].Descriptor()
	// listing.DefaultCreatedAt holds the default value on creation for the created_at field.
	listing.DefaultCreatedAt = listingDescCreatedAt.Default.(func() time.Time)
	// listingDescUpdatedAt is the schema descriptor for updated_at field.
	listingDescUpdatedAt := listingMixinFields1[1].Descriptor()
	// listing.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	listing.DefaultUpdatedAt = listingDescUpdatedAt.Default.(func() time.Time)
	// listing.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	listing.UpdateDefaultUpdatedAt = listingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// listingDescWizardStep is the schema descriptor for wizard_step field.
	listingDescWizardStep := listingFields[4].Descriptor()
	// listing.DefaultWizardStep holds the default value on creation for the wizard_step field.
	listing.DefaultWizardStep = listingDescWizardStep.Default.(string)
	// listing.WizardStepValidator is a validator for the "wizard_step" field. It is called by the builders before save.
	listing.WizardStepValidator = listingDescWizardStep.Validators[0].(func(string) error)
	// listingDescHeadline is the schema descriptor for headline field.
	listingDescHeadline := listingFields[5].Descriptor()
	// listing.HeadlineValidator is a validator for the "headline" field. It is called by the builders before save.
	listing.HeadlineValidator = listingDescHeadline.Validators[0].(func(string) error)
	// listingDescDescription is the schema descriptor for description field.
	listingDescDescription := listingFields[6].Descriptor()
	// listing.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	listing.DescriptionValidator = listingDescDescription.Validators[0].(func(string) error)
	// listingDescQualityScore is the schema descriptor for quality_score field.
	listingDescQualityScore := listingFields[9].Descriptor()
	// listing.DefaultQualityScore holds the default value on creation for the quality_score field.
	listing.DefaultQualityScore = listingDescQualityScore.Default.(int)
	// listing.QualityScoreValidator is a validator for the "quality_score" field. It is called by the builders before save.
	listing.QualityScoreValidator = func() func(int) error {
		validators := listingDescQualityScore.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(quality_score int) error {
			for _, fn := range fns {
				if err := fn(quality_score); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listingDescTrustScore is the schema descriptor for trust_score field.
	listingDescTrustScore := listingFields[10].Descriptor()
	// listing.DefaultTrustScore holds the default value on creation for the trust_score field.
	listing.DefaultTrustScore = listingDescTrustScore.Default.(int)
	// listing.TrustScoreValidator is a validator for the "trust_score" field. It is called by the builders before save.
	listing.TrustScoreValidator = func() func(int) error {
		validators := listingDescTrustScore.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(trust_score int) error {
			for _, fn := range fns {
				if err := fn(trust_score); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listingDescViewsCount is the schema descriptor for views_count field.
	listingDescViewsCount := listingFields[11].Descriptor()
	// listing.DefaultViewsCount holds the default value on creation for the views_count field.
	listing.DefaultViewsCount = listingDescViewsCount.Default.(int)
	// listing.ViewsCountValidator is a validator for the "views_count" field. It is called by the builders before save.
	listing.ViewsCountValidator = listingDescViewsCount.Validators[0].(func(int) error)
	// listingDescReviewNote is the schema descriptor for review_note field.
	listingDescReviewNote := listingFields[16].Descriptor()
	// listing.ReviewNoteValidator is a validator for the "review_note" field. It is called by the builders before save.
	listing.ReviewNoteValidator = listingDescReviewNote.Validators[0].(func(string) error)
	// listingDescID is the schema descriptor for id field.
	listingDescID := listingMixinFields0[0].Descriptor()
	// listing.DefaultID holds the default value on creation for the id field.
	listing.DefaultID = listingDescID.Default.(func() uuid.UUID)
	listingmediaMixin := schema.ListingMedia{}.Mixin()
	listingmediaMixinFields0 := listingmediaMixin[0].Fields()
	_ = listingmediaMixinFields0
	listingmediaMixinFields1 := listingmediaMixin[1].Fields()
	_ = listingmediaMixinFields1
	listingmediaFields := schema.ListingMedia{}.Fields()
	_ = listingmediaFields
	// listingmediaDescCreatedAt is the schema descriptor for created_at field.
	listingmediaDescCreatedAt := listingmediaMixinFields1[0].Descriptor()
	// listingmedia.DefaultCreatedAt holds the default value on creation for the created_at field.
	listingmedia.DefaultCreatedAt = listingmediaDescCreatedAt.Default.(func() time.Time)
	// listingmediaDescUpdatedAt is the schema descriptor for updated_at field.
	listingmediaDescUpdatedAt := listingmediaMixinFields1[1].Descriptor()
	// listingmedia.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	listingmedia.DefaultUpdatedAt = listingmediaDescUpdatedAt.Default.(func() time.Time)
	// listingmedia.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	listingmedia.UpdateDefaultUpdatedAt = listingmediaDescUpdatedAt.UpdateDefault.(func() time.Time)
	// listingmediaDescPosition is the schema descriptor for position field.
	listingmediaDescPosition := listingmediaFields[3].Descriptor()
	// listingmedia.DefaultPosition holds the default value on creation for the position field.
	listingmedia.DefaultPosition = listingmediaDescPosition.Default.(int)
	// listingmedia.PositionValidator is a validator for the "position" field. It is called by the builders before save.
	listingmedia.PositionValidator = listingmediaDescPosition.Validators[0].(func(int) error)
	// listingmediaDescWidth is the schema descriptor for width field.
	listingmediaDescWidth := listingmediaFields[5].Descriptor()
	// listingmedia.WidthValidator is a validator for the "width" field. It is called by the builders before save.
	listingmedia.WidthValidator = listingmediaDescWidth.Validators[0].(func(int) error)
	// listingmediaDescHeight is the schema descriptor for height field.
	listingmediaDescHeight := listingmediaFields[6].Descriptor()
	// listingmedia.HeightValidator is a validator for the "height" field. It is called by the builders before save.
	listingmedia.HeightValidator = listingmediaDescHeight.Validators[0].(func(int) error)
	// listingmediaDescBytes is the schema descriptor for bytes field.
	listingmediaDescBytes := listingmediaFields[7].Descriptor()
	// listingmedia.BytesValidator is a validator for the "bytes" field. It is called by the builders before save.
	listingmedia.BytesValidator = listingmediaDescBytes.Validators[0].(func(int) error)
	// listingmediaDescDurationMs is the schema descriptor for duration_ms field.
	listingmediaDescDurationMs := listingmediaFields[8].Descriptor()
	// listingmedia.DurationMsValidator is a validator for the "duration_ms" field. It is called by the builders before save.
	listingmedia.DurationMsValidator = listingmediaDescDurationMs.Validators[0].(func(int) error)
	// listingmediaDescBlurhash is the schema descriptor for blurhash field.
	listingmediaDescBlurhash := listingmediaFields[9].Descriptor()
	// listingmedia.BlurhashValidator is a validator for the "blurhash" field. It is called by the builders before save.
	listingmedia.BlurhashValidator = listingmediaDescBlurhash.Validators[0].(func(string) error)
	// listingmediaDescID is the schema descriptor for id field.
	listingmediaDescID := listingmediaMixinFields0[0].Descriptor()
	// listingmedia.DefaultID holds the default value on creation for the id field.
	listingmedia.DefaultID = listingmediaDescID.Default.(func() uuid.UUID)
	listingtermsMixin := schema.ListingTerms{}.Mixin()
	listingtermsMixinFields0 := listingtermsMixin[0].Fields()
	_ = listingtermsMixinFields0
	listingtermsMixinFields1 := listingtermsMixin[1].Fields()
	_ = listingtermsMixinFields1
	listingtermsFields := schema.ListingTerms{}.Fields()
	_ = listingtermsFields
	// listingtermsDescCreatedAt is the schema descriptor for created_at field.
	listingtermsDescCreatedAt := listingtermsMixinFields1[0].Descriptor()
	// listingterms.DefaultCreatedAt holds the default value on creation for the created_at field.
	listingterms.DefaultCreatedAt = listingtermsDescCreatedAt.Default.(func() time.Time)
	// listingtermsDescUpdatedAt is the schema descriptor for updated_at field.
	listingtermsDescUpdatedAt := listingtermsMixinFields1[1].Descriptor()
	// listingterms.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	listingterms.DefaultUpdatedAt = listingtermsDescUpdatedAt.Default.(func() time.Time)
	// listingterms.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	listingterms.UpdateDefaultUpdatedAt = listingtermsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// listingtermsDescRent is the schema descriptor for rent field.
	listingtermsDescRent := listingtermsFields[1].Descriptor()
	// listingterms.RentValidator is a validator for the "rent" field. It is called by the builders before save.
	listingterms.RentValidator = listingtermsDescRent.Validators[0].(func(int64) error)
	// listingtermsDescRentPeriod is the schema descriptor for rent_period field.
	listingtermsDescRentPeriod := listingtermsFields[2].Descriptor()
	// listingterms.DefaultRentPeriod holds the default value on creation for the rent_period field.
	listingterms.DefaultRentPeriod = listingtermsDescRentPeriod.Default.(string)
	// listingterms.RentPeriodValidator is a validator for the "rent_period" field. It is called by the builders before save.
	listingterms.RentPeriodValidator = listingtermsDescRentPeriod.Validators[0].(func(string) error)
	// listingtermsDescAdvancePeriods is the schema descriptor for advance_periods field.
	listingtermsDescAdvancePeriods := listingtermsFields[3].Descriptor()
	// listingterms.AdvancePeriodsValidator is a validator for the "advance_periods" field. It is called by the builders before save.
	listingterms.AdvancePeriodsValidator = func() func(int) error {
		validators := listingtermsDescAdvancePeriods.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(advance_periods int) error {
			for _, fn := range fns {
				if err := fn(advance_periods); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listingtermsDescDeposit is the schema descriptor for deposit field.
	listingtermsDescDeposit := listingtermsFields[4].Descriptor()
	// listingterms.DepositValidator is a validator for the "deposit" field. It is called by the builders before save.
	listingterms.DepositValidator = listingtermsDescDeposit.Validators[0].(func(int64) error)
	// listingtermsDescAgentFee is the schema descriptor for agent_fee field.
	listingtermsDescAgentFee := listingtermsFields[5].Descriptor()
	// listingterms.AgentFeeValidator is a validator for the "agent_fee" field. It is called by the builders before save.
	listingterms.AgentFeeValidator = listingtermsDescAgentFee.Validators[0].(func(int64) error)
	// listingtermsDescServiceCharge is the schema descriptor for service_charge field.
	listingtermsDescServiceCharge := listingtermsFields[6].Descriptor()
	// listingterms.ServiceChargeValidator is a validator for the "service_charge" field. It is called by the builders before save.
	listingterms.ServiceChargeValidator = listingtermsDescServiceCharge.Validators[0].(func(int64) error)
	// listingtermsDescViewingFee is the schema descriptor for viewing_fee field.
	listingtermsDescViewingFee := listingtermsFields[7].Descriptor()
	// listingterms.ViewingFeeValidator is a validator for the "viewing_fee" field. It is called by the builders before save.
	listingterms.ViewingFeeValidator = listingtermsDescViewingFee.Validators[0].(func(int64) error)
	// listingtermsDescMonthlyEquivalent is the schema descriptor for monthly_equivalent field.
	listingtermsDescMonthlyEquivalent := listingtermsFields[9].Descriptor()
	// listingterms.MonthlyEquivalentValidator is a validator for the "monthly_equivalent" field. It is called by the builders before save.
	listingterms.MonthlyEquivalentValidator = listingtermsDescMonthlyEquivalent.Validators[0].(func(int64) error)
	// listingtermsDescMoveInTotal is the schema descriptor for move_in_total field.
	listingtermsDescMoveInTotal := listingtermsFields[10].Descriptor()
	// listingterms.MoveInTotalValidator is a validator for the "move_in_total" field. It is called by the builders before save.
	listingterms.MoveInTotalValidator = listingtermsDescMoveInTotal.Validators[0].(func(int64) error)
	// listingtermsDescNegotiable is the schema descriptor for negotiable field.
	listingtermsDescNegotiable := listingtermsFields[11].Descriptor()
	// listingterms.DefaultNegotiable holds the default value on creation for the negotiable field.
	listingterms.DefaultNegotiable = listingtermsDescNegotiable.Default.(bool)
	// listingtermsDescMinLeaseMonths is the schema descriptor for min_lease_months field.
	listingtermsDescMinLeaseMonths := listingtermsFields[12].Descriptor()
	// listingterms.MinLeaseMonthsValidator is a validator for the "min_lease_months" field. It is called by the builders before save.
	listingterms.MinLeaseMonthsValidator = func() func(int) error {
		validators := listingtermsDescMinLeaseMonths.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(min_lease_months int) error {
			for _, fn := range fns {
				if err := fn(min_lease_months); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// listingtermsDescID is the schema descriptor for id field.
	listingtermsDescID := listingtermsMixinFields0[0].Descriptor()
	// listingterms.DefaultID holds the default value on creation for the id field.
	listingterms.DefaultID = listingtermsDescID.Default.(func() uuid.UUID)
	otpcodeMixin := schema.OTPCode{}.Mixin()
	otpcodeMixinFields0 := otpcodeMixin[0].Fields()
	_ = otpcodeMixinFields0
	otpcodeMixinFields1 := otpcodeMixin[1].Fields()
	_ = otpcodeMixinFields1
	otpcodeFields := schema.OTPCode{}.Fields()
	_ = otpcodeFields
	// otpcodeDescCreatedAt is the schema descriptor for created_at field.
	otpcodeDescCreatedAt := otpcodeMixinFields1[0].Descriptor()
	// otpcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	otpcode.DefaultCreatedAt = otpcodeDescCreatedAt.Default.(func() time.Time)
	// otpcodeDescUpdatedAt is the schema descriptor for updated_at field.
	otpcodeDescUpdatedAt := otpcodeMixinFields1[1].Descriptor()
	// otpcode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	otpcode.DefaultUpdatedAt = otpcodeDescUpdatedAt.Default.(func() time.Time)
	// otpcode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	otpcode.UpdateDefaultUpdatedAt = otpcodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// otpcodeDescPhone is the schema descriptor for phone field.
	otpcodeDescPhone := otpcodeFields[0].Descriptor()
	// otpcode.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	otpcode.PhoneValidator = func() func(string) error {
		validators := otpcodeDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// otpcodeDescCodeHash is the schema descriptor for code_hash field.
	otpcodeDescCodeHash := otpcodeFields[1].Descriptor()
	// otpcode.CodeHashValidator is a validator for the "code_hash" field. It is called by the builders before save.
	otpcode.CodeHashValidator = otpcodeDescCodeHash.Validators[0].(func([]byte) error)
	// otpcodeDescAttempts is the schema descriptor for attempts field.
	otpcodeDescAttempts := otpcodeFields[2].Descriptor()
	// otpcode.DefaultAttempts holds the default value on creation for the attempts field.
	otpcode.DefaultAttempts = otpcodeDescAttempts.Default.(int)
	// otpcode.AttemptsValidator is a validator for the "attempts" field. It is called by the builders before save.
	otpcode.AttemptsValidator = otpcodeDescAttempts.Validators[0].(func(int) error)
	// otpcodeDescChannel is the schema descriptor for channel field.
	otpcodeDescChannel := otpcodeFields[5].Descriptor()
	// otpcode.DefaultChannel holds the default value on creation for the channel field.
	otpcode.DefaultChannel = otpcodeDescChannel.Default.(string)
	// otpcode.ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	otpcode.ChannelValidator = otpcodeDescChannel.Validators[0].(func(string) error)
	// otpcodeDescIP is the schema descriptor for ip field.
	otpcodeDescIP := otpcodeFields[6].Descriptor()
	// otpcode.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	otpcode.IPValidator = otpcodeDescIP.Validators[0].(func(string) error)
	// otpcodeDescID is the schema descriptor for id field.
	otpcodeDescID := otpcodeMixinFields0[0].Descriptor()
	// otpcode.DefaultID holds the default value on creation for the id field.
	otpcode.DefaultID = otpcodeDescID.Default.(func() uuid.UUID)
	propertyMixin := schema.Property{}.Mixin()
	propertyMixinFields0 := propertyMixin[0].Fields()
	_ = propertyMixinFields0
	propertyMixinFields1 := propertyMixin[1].Fields()
	_ = propertyMixinFields1
	propertyFields := schema.Property{}.Fields()
	_ = propertyFields
	// propertyDescCreatedAt is the schema descriptor for created_at field.
	propertyDescCreatedAt := propertyMixinFields1[0].Descriptor()
	// property.DefaultCreatedAt holds the default value on creation for the created_at field.
	property.DefaultCreatedAt = propertyDescCreatedAt.Default.(func() time.Time)
	// propertyDescUpdatedAt is the schema descriptor for updated_at field.
	propertyDescUpdatedAt := propertyMixinFields1[1].Descriptor()
	// property.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	property.DefaultUpdatedAt = propertyDescUpdatedAt.Default.(func() time.Time)
	// property.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	property.UpdateDefaultUpdatedAt = propertyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// propertyDescName is the schema descriptor for name field.
	propertyDescName := propertyFields[2].Descriptor()
	// property.NameValidator is a validator for the "name" field. It is called by the builders before save.
	property.NameValidator = propertyDescName.Validators[0].(func(string) error)
	// propertyDescCategory is the schema descriptor for category field.
	propertyDescCategory := propertyFields[3].Descriptor()
	// property.DefaultCategory holds the default value on creation for the category field.
	property.DefaultCategory = propertyDescCategory.Default.(string)
	// property.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	property.CategoryValidator = propertyDescCategory.Validators[0].(func(string) error)
	// propertyDescDigitalAddress is the schema descriptor for digital_address field.
	propertyDescDigitalAddress := propertyFields[8].Descriptor()
	// property.DigitalAddressValidator is a validator for the "digital_address" field. It is called by the builders before save.
	property.DigitalAddressValidator = propertyDescDigitalAddress.Validators[0].(func(string) error)
	// propertyDescLandmark is the schema descriptor for landmark field.
	propertyDescLandmark := propertyFields[9].Descriptor()
	// property.LandmarkValidator is a validator for the "landmark" field. It is called by the builders before save.
	property.LandmarkValidator = propertyDescLandmark.Validators[0].(func(string) error)
	// propertyDescStreet is the schema descriptor for street field.
	propertyDescStreet := propertyFields[10].Descriptor()
	// property.StreetValidator is a validator for the "street" field. It is called by the builders before save.
	property.StreetValidator = propertyDescStreet.Validators[0].(func(string) error)
	// propertyDescNeighbourhood is the schema descriptor for neighbourhood field.
	propertyDescNeighbourhood := propertyFields[11].Descriptor()
	// property.NeighbourhoodValidator is a validator for the "neighbourhood" field. It is called by the builders before save.
	property.NeighbourhoodValidator = propertyDescNeighbourhood.Validators[0].(func(string) error)
	// propertyDescCity is the schema descriptor for city field.
	propertyDescCity := propertyFields[12].Descriptor()
	// property.DefaultCity holds the default value on creation for the city field.
	property.DefaultCity = propertyDescCity.Default.(string)
	// property.CityValidator is a validator for the "city" field. It is called by the builders before save.
	property.CityValidator = propertyDescCity.Validators[0].(func(string) error)
	// propertyDescRegion is the schema descriptor for region field.
	propertyDescRegion := propertyFields[13].Descriptor()
	// property.DefaultRegion holds the default value on creation for the region field.
	property.DefaultRegion = propertyDescRegion.Default.(string)
	// property.RegionValidator is a validator for the "region" field. It is called by the builders before save.
	property.RegionValidator = propertyDescRegion.Validators[0].(func(string) error)
	// propertyDescID is the schema descriptor for id field.
	propertyDescID := propertyMixinFields0[0].Descriptor()
	// property.DefaultID holds the default value on creation for the id field.
	property.DefaultID = propertyDescID.Default.(func() uuid.UUID)
	roleassignmentMixin := schema.RoleAssignment{}.Mixin()
	roleassignmentMixinFields0 := roleassignmentMixin[0].Fields()
	_ = roleassignmentMixinFields0
	roleassignmentMixinFields1 := roleassignmentMixin[1].Fields()
	_ = roleassignmentMixinFields1
	roleassignmentFields := schema.RoleAssignment{}.Fields()
	_ = roleassignmentFields
	// roleassignmentDescCreatedAt is the schema descriptor for created_at field.
	roleassignmentDescCreatedAt := roleassignmentMixinFields1[0].Descriptor()
	// roleassignment.DefaultCreatedAt holds the default value on creation for the created_at field.
	roleassignment.DefaultCreatedAt = roleassignmentDescCreatedAt.Default.(func() time.Time)
	// roleassignmentDescUpdatedAt is the schema descriptor for updated_at field.
	roleassignmentDescUpdatedAt := roleassignmentMixinFields1[1].Descriptor()
	// roleassignment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	roleassignment.DefaultUpdatedAt = roleassignmentDescUpdatedAt.Default.(func() time.Time)
	// roleassignment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	roleassignment.UpdateDefaultUpdatedAt = roleassignmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleassignmentDescID is the schema descriptor for id field.
	roleassignmentDescID := roleassignmentMixinFields0[0].Descriptor()
	// roleassignment.DefaultID holds the default value on creation for the id field.
	roleassignment.DefaultID = roleassignmentDescID.Default.(func() uuid.UUID)
	savedlistingMixin := schema.SavedListing{}.Mixin()
	savedlistingMixinFields0 := savedlistingMixin[0].Fields()
	_ = savedlistingMixinFields0
	savedlistingMixinFields1 := savedlistingMixin[1].Fields()
	_ = savedlistingMixinFields1
	savedlistingFields := schema.SavedListing{}.Fields()
	_ = savedlistingFields
	// savedlistingDescCreatedAt is the schema descriptor for created_at field.
	savedlistingDescCreatedAt := savedlistingMixinFields1[0].Descriptor()
	// savedlisting.DefaultCreatedAt holds the default value on creation for the created_at field.
	savedlisting.DefaultCreatedAt = savedlistingDescCreatedAt.Default.(func() time.Time)
	// savedlistingDescUpdatedAt is the schema descriptor for updated_at field.
	savedlistingDescUpdatedAt := savedlistingMixinFields1[1].Descriptor()
	// savedlisting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	savedlisting.DefaultUpdatedAt = savedlistingDescUpdatedAt.Default.(func() time.Time)
	// savedlisting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	savedlisting.UpdateDefaultUpdatedAt = savedlistingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// savedlistingDescID is the schema descriptor for id field.
	savedlistingDescID := savedlistingMixinFields0[0].Descriptor()
	// savedlisting.DefaultID holds the default value on creation for the id field.
	savedlisting.DefaultID = savedlistingDescID.Default.(func() uuid.UUID)
	sessionMixin := schema.Session{}.Mixin()
	sessionMixinFields0 := sessionMixin[0].Fields()
	_ = sessionMixinFields0
	sessionMixinFields1 := sessionMixin[1].Fields()
	_ = sessionMixinFields1
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionMixinFields1[0].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionMixinFields1[1].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[0].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func([]byte) error)
	// sessionDescUserAgent is the schema descriptor for user_agent field.
	sessionDescUserAgent := sessionFields[2].Descriptor()
	// session.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	session.UserAgentValidator = sessionDescUserAgent.Validators[0].(func(string) error)
	// sessionDescIP is the schema descriptor for ip field.
	sessionDescIP := sessionFields[3].Descriptor()
	// session.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	session.IPValidator = sessionDescIP.Validators[0].(func(string) error)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionMixinFields0[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	unitMixin := schema.Unit{}.Mixin()
	unitMixinFields0 := unitMixin[0].Fields()
	_ = unitMixinFields0
	unitMixinFields1 := unitMixin[1].Fields()
	_ = unitMixinFields1
	unitFields := schema.Unit{}.Fields()
	_ = unitFields
	// unitDescCreatedAt is the schema descriptor for created_at field.
	unitDescCreatedAt := unitMixinFields1[0].Descriptor()
	// unit.DefaultCreatedAt holds the default value on creation for the created_at field.
	unit.DefaultCreatedAt = unitDescCreatedAt.Default.(func() time.Time)
	// unitDescUpdatedAt is the schema descriptor for updated_at field.
	unitDescUpdatedAt := unitMixinFields1[1].Descriptor()
	// unit.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	unit.DefaultUpdatedAt = unitDescUpdatedAt.Default.(func() time.Time)
	// unit.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	unit.UpdateDefaultUpdatedAt = unitDescUpdatedAt.UpdateDefault.(func() time.Time)
	// unitDescLabel is the schema descriptor for label field.
	unitDescLabel := unitFields[1].Descriptor()
	// unit.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	unit.LabelValidator = unitDescLabel.Validators[0].(func(string) error)
	// unitDescUnitType is the schema descriptor for unit_type field.
	unitDescUnitType := unitFields[2].Descriptor()
	// unit.UnitTypeValidator is a validator for the "unit_type" field. It is called by the builders before save.
	unit.UnitTypeValidator = unitDescUnitType.Validators[0].(func(string) error)
	// unitDescBedrooms is the schema descriptor for bedrooms field.
	unitDescBedrooms := unitFields[3].Descriptor()
	// unit.BedroomsValidator is a validator for the "bedrooms" field. It is called by the builders before save.
	unit.BedroomsValidator = unitDescBedrooms.Validators[0].(func(int) error)
	// unitDescBathrooms is the schema descriptor for bathrooms field.
	unitDescBathrooms := unitFields[4].Descriptor()
	// unit.BathroomsValidator is a validator for the "bathrooms" field. It is called by the builders before save.
	unit.BathroomsValidator = unitDescBathrooms.Validators[0].(func(int) error)
	// unitDescSizeSqm is the schema descriptor for size_sqm field.
	unitDescSizeSqm := unitFields[5].Descriptor()
	// unit.SizeSqmValidator is a validator for the "size_sqm" field. It is called by the builders before save.
	unit.SizeSqmValidator = unitDescSizeSqm.Validators[0].(func(int) error)
	// unitDescFurnished is the schema descriptor for furnished field.
	unitDescFurnished := unitFields[7].Descriptor()
	// unit.FurnishedValidator is a validator for the "furnished" field. It is called by the builders before save.
	unit.FurnishedValidator = unitDescFurnished.Validators[0].(func(string) error)
	// unitDescMeterType is the schema descriptor for meter_type field.
	unitDescMeterType := unitFields[9].Descriptor()
	// unit.MeterTypeValidator is a validator for the "meter_type" field. It is called by the builders before save.
	unit.MeterTypeValidator = unitDescMeterType.Validators[0].(func(string) error)
	// unitDescWaterSource is the schema descriptor for water_source field.
	unitDescWaterSource := unitFields[10].Descriptor()
	// unit.WaterSourceValidator is a validator for the "water_source" field. It is called by the builders before save.
	unit.WaterSourceValidator = unitDescWaterSource.Validators[0].(func(string) error)
	// unitDescKitchen is the schema descriptor for kitchen field.
	unitDescKitchen := unitFields[11].Descriptor()
	// unit.KitchenValidator is a validator for the "kitchen" field. It is called by the builders before save.
	unit.KitchenValidator = unitDescKitchen.Validators[0].(func(string) error)
	// unitDescID is the schema descriptor for id field.
	unitDescID := unitMixinFields0[0].Descriptor()
	// unit.DefaultID holds the default value on creation for the id field.
	unit.DefaultID = unitDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[0].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = func() func(string) error {
		validators := userDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescAvatarKey is the schema descriptor for avatar_key field.
	userDescAvatarKey := userFields[7].Descriptor()
	// user.AvatarKeyValidator is a validator for the "avatar_key" field. It is called by the builders before save.
	user.AvatarKeyValidator = userDescAvatarKey.Validators[0].(func(string) error)
	// userDescDataSaver is the schema descriptor for data_saver field.
	userDescDataSaver := userFields[8].Descriptor()
	// user.DefaultDataSaver holds the default value on creation for the data_saver field.
	user.DefaultDataSaver = userDescDataSaver.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	verificationMixin := schema.Verification{}.Mixin()
	verification.Policy = privacy.NewPolicies(schema.Verification{})
	verification.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := verification.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	verificationMixinFields0 := verificationMixin[0].Fields()
	_ = verificationMixinFields0
	verificationMixinFields1 := verificationMixin[1].Fields()
	_ = verificationMixinFields1
	verificationFields := schema.Verification{}.Fields()
	_ = verificationFields
	// verificationDescCreatedAt is the schema descriptor for created_at field.
	verificationDescCreatedAt := verificationMixinFields1[0].Descriptor()
	// verification.DefaultCreatedAt holds the default value on creation for the created_at field.
	verification.DefaultCreatedAt = verificationDescCreatedAt.Default.(func() time.Time)
	// verificationDescUpdatedAt is the schema descriptor for updated_at field.
	verificationDescUpdatedAt := verificationMixinFields1[1].Descriptor()
	// verification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	verification.DefaultUpdatedAt = verificationDescUpdatedAt.Default.(func() time.Time)
	// verification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	verification.UpdateDefaultUpdatedAt = verificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// verificationDescMethod is the schema descriptor for method field.
	verificationDescMethod := verificationFields[3].Descriptor()
	// verification.DefaultMethod holds the default value on creation for the method field.
	verification.DefaultMethod = verificationDescMethod.Default.(string)
	// verification.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	verification.MethodValidator = verificationDescMethod.Validators[0].(func(string) error)
	// verificationDescIDNumberLast4 is the schema descriptor for id_number_last4 field.
	verificationDescIDNumberLast4 := verificationFields[5].Descriptor()
	// verification.IDNumberLast4Validator is a validator for the "id_number_last4" field. It is called by the builders before save.
	verification.IDNumberLast4Validator = verificationDescIDNumberLast4.Validators[0].(func(string) error)
	// verificationDescLicenseNumber is the schema descriptor for license_number field.
	verificationDescLicenseNumber := verificationFields[6].Descriptor()
	// verification.LicenseNumberValidator is a validator for the "license_number" field. It is called by the builders before save.
	verification.LicenseNumberValidator = verificationDescLicenseNumber.Validators[0].(func(string) error)
	// verificationDescDecisionReason is the schema descriptor for decision_reason field.
	verificationDescDecisionReason := verificationFields[9].Descriptor()
	// verification.DecisionReasonValidator is a validator for the "decision_reason" field. It is called by the builders before save.
	verification.DecisionReasonValidator = verificationDescDecisionReason.Validators[0].(func(string) error)
	// verificationDescDecisionNote is the schema descriptor for decision_note field.
	verificationDescDecisionNote := verificationFields[10].Descriptor()
	// verification.DecisionNoteValidator is a validator for the "decision_note" field. It is called by the builders before save.
	verification.DecisionNoteValidator = verificationDescDecisionNote.Validators[0].(func(string) error)
	// verificationDescID is the schema descriptor for id field.
	verificationDescID := verificationMixinFields0[0].Descriptor()
	// verification.DefaultID holds the default value on creation for the id field.
	verification.DefaultID = verificationDescID.Default.(func() uuid.UUID)
	verificationfileMixin := schema.VerificationFile{}.Mixin()
	verificationfile.Policy = privacy.NewPolicies(schema.VerificationFile{})
	verificationfile.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := verificationfile.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	verificationfileMixinFields0 := verificationfileMixin[0].Fields()
	_ = verificationfileMixinFields0
	verificationfileMixinFields1 := verificationfileMixin[1].Fields()
	_ = verificationfileMixinFields1
	verificationfileFields := schema.VerificationFile{}.Fields()
	_ = verificationfileFields
	// verificationfileDescCreatedAt is the schema descriptor for created_at field.
	verificationfileDescCreatedAt := verificationfileMixinFields1[0].Descriptor()
	// verificationfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	verificationfile.DefaultCreatedAt = verificationfileDescCreatedAt.Default.(func() time.Time)
	// verificationfileDescUpdatedAt is the schema descriptor for updated_at field.
	verificationfileDescUpdatedAt := verificationfileMixinFields1[1].Descriptor()
	// verificationfile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	verificationfile.DefaultUpdatedAt = verificationfileDescUpdatedAt.Default.(func() time.Time)
	// verificationfile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	verificationfile.UpdateDefaultUpdatedAt = verificationfileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// verificationfileDescStorageKey is the schema descriptor for storage_key field.
	verificationfileDescStorageKey := verificationfileFields[3].Descriptor()
	// verificationfile.StorageKeyValidator is a validator for the "storage_key" field. It is called by the builders before save.
	verificationfile.StorageKeyValidator = verificationfileDescStorageKey.Validators[0].(func(string) error)
	// verificationfileDescContentType is the schema descriptor for content_type field.
	verificationfileDescContentType := verificationfileFields[4].Descriptor()
	// verificationfile.ContentTypeValidator is a validator for the "content_type" field. It is called by the builders before save.
	verificationfile.ContentTypeValidator = verificationfileDescContentType.Validators[0].(func(string) error)
	// verificationfileDescSize is the schema descriptor for size field.
	verificationfileDescSize := verificationfileFields[5].Descriptor()
	// verificationfile.SizeValidator is a validator for the "size" field. It is called by the builders before save.
	verificationfile.SizeValidator = verificationfileDescSize.Validators[0].(func(int) error)
	// verificationfileDescID is the schema descriptor for id field.
	verificationfileDescID := verificationfileMixinFields0[0].Descriptor()
	// verificationfile.DefaultID holds the default value on creation for the id field.
	verificationfile.DefaultID = verificationfileDescID.Default.(func() uuid.UUID)
	viewingMixin := schema.Viewing{}.Mixin()
	viewingMixinFields0 := viewingMixin[0].Fields()
	_ = viewingMixinFields0
	viewingMixinFields1 := viewingMixin[1].Fields()
	_ = viewingMixinFields1
	viewingFields := schema.Viewing{}.Fields()
	_ = viewingFields
	// viewingDescCreatedAt is the schema descriptor for created_at field.
	viewingDescCreatedAt := viewingMixinFields1[0].Descriptor()
	// viewing.DefaultCreatedAt holds the default value on creation for the created_at field.
	viewing.DefaultCreatedAt = viewingDescCreatedAt.Default.(func() time.Time)
	// viewingDescUpdatedAt is the schema descriptor for updated_at field.
	viewingDescUpdatedAt := viewingMixinFields1[1].Descriptor()
	// viewing.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	viewing.DefaultUpdatedAt = viewingDescUpdatedAt.Default.(func() time.Time)
	// viewing.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	viewing.UpdateDefaultUpdatedAt = viewingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// viewingDescDurationMin is the schema descriptor for duration_min field.
	viewingDescDurationMin := viewingFields[5].Descriptor()
	// viewing.DefaultDurationMin holds the default value on creation for the duration_min field.
	viewing.DefaultDurationMin = viewingDescDurationMin.Default.(int)
	// viewing.DurationMinValidator is a validator for the "duration_min" field. It is called by the builders before save.
	viewing.DurationMinValidator = viewingDescDurationMin.Validators[0].(func(int) error)
	// viewingDescNote is the schema descriptor for note field.
	viewingDescNote := viewingFields[6].Descriptor()
	// viewing.NoteValidator is a validator for the "note" field. It is called by the builders before save.
	viewing.NoteValidator = viewingDescNote.Validators[0].(func(string) error)
	// viewingDescFeeAcknowledged is the schema descriptor for fee_acknowledged field.
	viewingDescFeeAcknowledged := viewingFields[8].Descriptor()
	// viewing.DefaultFeeAcknowledged holds the default value on creation for the fee_acknowledged field.
	viewing.DefaultFeeAcknowledged = viewingDescFeeAcknowledged.Default.(bool)
	// viewingDescDeclineReason is the schema descriptor for decline_reason field.
	viewingDescDeclineReason := viewingFields[9].Descriptor()
	// viewing.DeclineReasonValidator is a validator for the "decline_reason" field. It is called by the builders before save.
	viewing.DeclineReasonValidator = viewingDescDeclineReason.Validators[0].(func(string) error)
	// viewingDescID is the schema descriptor for id field.
	viewingDescID := viewingMixinFields0[0].Descriptor()
	// viewing.DefaultID holds the default value on creation for the id field.
	viewing.DefaultID = viewingDescID.Default.(func() uuid.UUID)
	waitlistentryMixin := schema.WaitlistEntry{}.Mixin()
	waitlistentryMixinFields0 := waitlistentryMixin[0].Fields()
	_ = waitlistentryMixinFields0
	waitlistentryMixinFields1 := waitlistentryMixin[1].Fields()
	_ = waitlistentryMixinFields1
	waitlistentryFields := schema.WaitlistEntry{}.Fields()
	_ = waitlistentryFields
	// waitlistentryDescCreatedAt is the schema descriptor for created_at field.
	waitlistentryDescCreatedAt := waitlistentryMixinFields1[0].Descriptor()
	// waitlistentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	waitlistentry.DefaultCreatedAt = waitlistentryDescCreatedAt.Default.(func() time.Time)
	// waitlistentryDescUpdatedAt is the schema descriptor for updated_at field.
	waitlistentryDescUpdatedAt := waitlistentryMixinFields1[1].Descriptor()
	// waitlistentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	waitlistentry.DefaultUpdatedAt = waitlistentryDescUpdatedAt.Default.(func() time.Time)
	// waitlistentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	waitlistentry.UpdateDefaultUpdatedAt = waitlistentryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// waitlistentryDescPhone is the schema descriptor for phone field.
	waitlistentryDescPhone := waitlistentryFields[0].Descriptor()
	// waitlistentry.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	waitlistentry.PhoneValidator = func() func(string) error {
		validators := waitlistentryDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// waitlistentryDescName is the schema descriptor for name field.
	waitlistentryDescName := waitlistentryFields[1].Descriptor()
	// waitlistentry.NameValidator is a validator for the "name" field. It is called by the builders before save.
	waitlistentry.NameValidator = waitlistentryDescName.Validators[0].(func(string) error)
	// waitlistentryDescArea is the schema descriptor for area field.
	waitlistentryDescArea := waitlistentryFields[3].Descriptor()
	// waitlistentry.AreaValidator is a validator for the "area" field. It is called by the builders before save.
	waitlistentry.AreaValidator = waitlistentryDescArea.Validators[0].(func(string) error)
	// waitlistentryDescSource is the schema descriptor for source field.
	waitlistentryDescSource := waitlistentryFields[4].Descriptor()
	// waitlistentry.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	waitlistentry.SourceValidator = waitlistentryDescSource.Validators[0].(func(string) error)
	// waitlistentryDescConsent is the schema descriptor for consent field.
	waitlistentryDescConsent := waitlistentryFields[5].Descriptor()
	// waitlistentry.DefaultConsent holds the default value on creation for the consent field.
	waitlistentry.DefaultConsent = waitlistentryDescConsent.Default.(bool)
	// waitlistentryDescID is the schema descriptor for id field.
	waitlistentryDescID := waitlistentryMixinFields0[0].Descriptor()
	// waitlistentry.DefaultID holds the default value on creation for the id field.
	waitlistentry.DefaultID = waitlistentryDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
